In [18]:
import numpy as np
import pandas as pd

In [19]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

In [20]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [21]:
df['Sex'].value_counts()

F    2
M    1
D    1
?    1
Name: Sex, dtype: int64

In [22]:
df['Sex'].replace('D', 'F')

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [23]:
df['Sex'].replace({'D': 'F', 'N': 'M'})

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [24]:
df.replace({
    'Sex': {
        'D': 'F',
        'N': 'M'
    },
    'Age': {
        290: 29
    }
})

  Sex  Age
0   M   29
1   F   30
2   F   24
3   F   29
4   ?   25

In [25]:
df[df['Age'] > 100]

  Sex  Age
3   D  290

In [26]:
df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age'] /10

In [27]:
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D   29
4   ?   25

In [16]:
ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gérard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth '
])

In [17]:
ambassadors

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

In [18]:
ambassadors.duplicated()

Gérard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [19]:
ambassadors.duplicated(keep='last')

Gérard Araud          False
Kim Darroch            True
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

In [21]:
ambassadors

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

In [20]:

ambassadors.duplicated(keep=False)

Gérard Araud          False
Kim Darroch            True
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [22]:
ambassadors.drop_duplicates()

Gérard Araud                  France
Kim Darroch           United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
dtype: object

In [23]:
ambassadors.drop_duplicates(keep='last')

Gérard Araud                  France
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Klaus Scharioth              Germany
dtype: object

In [24]:
ambassadors.drop_duplicates(keep=False)

Gérard Araud          France
Armando Varricchio     Italy
dtype: object

In [ ]:
#Duplicates in DataFrames

In [25]:
players = pd.DataFrame({
    'Name': [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Pos': [
        'SG',
        'SF',
        'SG',
        'SF',
        'SF'
    ]
})

In [26]:
players

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
2      Kobe Bryant  SG
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [27]:
players.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [30]:
players.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [31]:
players.duplicated(subset=['Name'], keep='last')

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [32]:
players.drop_duplicates()

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [33]:
players.drop_duplicates(subset=['Name'])

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF

In [34]:
#text handaling

In [35]:
df = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})

In [36]:
df

              Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [37]:

df['Data'].str.split('_')

0       [1987, M, US , 1]
1       [1990?, M, UK, 1]
2        [1992, F, US, 2]
3    [1970?, M,    IT, 1]
4      [1985, F, I  T, 2]
Name: Data, dtype: object

In [38]:
df['Data'].str.split('_', expand=True)

       0  1      2  3
0   1987  M    US   1
1  1990?  M     UK  1
2   1992  F     US  2
3  1970?  M     IT  1
4   1985  F   I  T  2

In [39]:
df = df['Data'].str.split('_', expand=True)

In [42]:
df.columns = ['Year', 'Sex', 'Country', 'No. Of Children']

In [43]:
df

    Year Sex Country No. Of Children
0   1987   M     US                1
1  1990?   M      UK               1
2   1992   F      US               2
3  1970?   M      IT               1
4   1985   F    I  T               2

In [46]:
df['Year'].str.contains('/?')

0    True
1    True
2    True
3    True
4    True
Name: Year, dtype: bool

In [47]:
df['Country'].str.contains('U')

0     True
1     True
2     True
3    False
4    False
Name: Country, dtype: bool

In [48]:
df['Country'].str.strip()

0      US
1      UK
2      US
3      IT
4    I  T
Name: Country, dtype: object

In [49]:
df['Country'].str.replace(' ', '')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object

In [56]:
df['Year'].str.replace('?', '')

C:\Users\91968\AppData\Local\Temp\ipykernel_31680\3542590379.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Year'].str.replace('?', '')

0    1987
1    1990
2    1992
3    1970
4    1985
Name: Year, dtype: object

In [57]:
df["Year"]

0     1987
1    1990?
2     1992
3    1970?
4     1985
Name: Year, dtype: object

In [58]:
df['Year'].str.replace(r'(?P\d{4})\?', lambda m: m.group('year'))

C:\Users\91968\AppData\Local\Temp\ipykernel_31680\3174302494.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Year'].str.replace(r'(?P\d{4})\?', lambda m: m.group('year'))

error: unknown extension ?P\d at position 1