In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
})

In [4]:
df

   Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [5]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [6]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [7]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [8]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [9]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [10]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [11]:
df.loc['Italy']

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [12]:
df.loc['France':'Italy']

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [13]:
df.loc['France':'Italy','Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [14]:
df.loc['France':'Italy',['Population','GDP']]

         Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [15]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [16]:
df.iloc[[0,3,-1]]

               Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
Italy              60.665   2167744        301336  0.873    Europe
United States     318.523  17348075       9525067  0.915   America

In [17]:
df.iloc[[1,4]]

        Population      GDP  Surface Area    HDI Continent
France      63.951  2833687        640679  0.888    Europe
Japan      127.061  4602367        377930  0.891      Asia

In [18]:
df.iloc[2:]

                Population       GDP  Surface Area    HDI Continent
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [19]:
df.iloc[0:3,4]

Canada     America
France      Europe
Germany     Europe
Name: Continent, dtype: object

In [20]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [21]:
df['Population']>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [22]:
df.loc[df['Population']>70]

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [23]:
df.loc[df['Population']>70,"Population"]

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [24]:
df.loc[df['Population']>70,["Population","GDP"]]

               Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

In [25]:
df.drop("Canada")

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [26]:
df.drop(["Canada","Japan","Italy"])

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [27]:
df.drop(["Population","HDI"],axis=1)

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [28]:
df[["GDP","Population"]]

                     GDP  Population
Canada           1785387      35.467
France           2833687      63.951
Germany          3874437      80.940
Italy            2167744      60.665
Japan            4602367     127.061
United Kingdom   2950039      64.511
United States   17348075     318.523

In [29]:
df[['Population', 'GDP']] / 100

                Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

In [30]:
df.drop('Canada')

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [31]:
df.drop(columns=['Population','HDI'])

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [79]:
df.drop(['Italy','Canada'],axis=0)

,Population,GDP,Surface Area,HDI,Continent,Language,GDP Per Capita
France,63.951,2833687,640679,0.888,america,French,44310.284437
Germany,80.940,3874437,357114,0.916,america,German,47868.013343
Japan,127.061,4602367,377930,0.891,america,NaN,36221.712406
United Kingdom,64.511,2950039,242495,0.907,america,NaN,45729.239975
United States,318.523,17348075,9525067,0.915,america,NaN,54464.120330

In [33]:
crisis = pd.Series([-1_000_000, -0.3], index=['GDP', 'HDI'])
crisis

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [34]:
df[['GDP','HDI']]

                     GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [35]:
df[['GDP','HDI']]+crisis

                       GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

In [36]:
langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)

In [37]:
langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: object

In [38]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [39]:
df['Language'] = langs

In [40]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [41]:
df['Continent']='america'

In [42]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   america      NaN
France              63.951   2833687        640679  0.888   america   French
Germany             80.940   3874437        357114  0.916   america   German
Italy               60.665   2167744        301336  0.873   america  Italian
Japan              127.061   4602367        377930  0.891   america      NaN
United Kingdom      64.511   2950039        242495  0.907   america      NaN
United States      318.523  17348075       9525067  0.915   america      NaN

In [43]:
df.rename(
    columns={
        'HDI': 'Human Development Index',
        'Anual Popcorn Consumption': 'APC'
    }, index={
        'United States': 'USA',
        'United Kingdom': 'UK',
        'Argentina': 'AR'
    })

,Population,GDP,Surface Area,Human Development Index,Continent,Language
Canada,35.467,1785387,9984670,0.913,america,NaN
France,63.951,2833687,640679,0.888,america,French
Germany,80.940,3874437,357114,0.916,america,German
Italy,60.665,2167744,301336,0.873,america,Italian
Japan,127.061,4602367,377930,0.891,america,NaN
UK,64.511,2950039,242495,0.907,america,NaN
USA,318.523,17348075,9525067,0.915,america,NaN

In [44]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   america      NaN
France              63.951   2833687        640679  0.888   america   French
Germany             80.940   3874437        357114  0.916   america   German
Italy               60.665   2167744        301336  0.873   america  Italian
Japan              127.061   4602367        377930  0.891   america      NaN
United Kingdom      64.511   2950039        242495  0.907   america      NaN
United States      318.523  17348075       9525067  0.915   america      NaN

In [46]:
df.rename(index=str.upper)

                Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   america      NaN
FRANCE              63.951   2833687        640679  0.888   america   French
GERMANY             80.940   3874437        357114  0.916   america   German
ITALY               60.665   2167744        301336  0.873   america  Italian
JAPAN              127.061   4602367        377930  0.891   america      NaN
UNITED KINGDOM      64.511   2950039        242495  0.907   america      NaN
UNITED STATES      318.523  17348075       9525067  0.915   america      NaN

In [47]:
df.rename(index=lambda x: x.lower())

                Population       GDP  Surface Area    HDI Continent Language
canada              35.467   1785387       9984670  0.913   america      NaN
france              63.951   2833687        640679  0.888   america   French
germany             80.940   3874437        357114  0.916   america   German
italy               60.665   2167744        301336  0.873   america  Italian
japan              127.061   4602367        377930  0.891   america      NaN
united kingdom      64.511   2950039        242495  0.907   america      NaN
united states      318.523  17348075       9525067  0.915   america      NaN

In [48]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   america      NaN
France              63.951   2833687        640679  0.888   america   French
Germany             80.940   3874437        357114  0.916   america   German
Italy               60.665   2167744        301336  0.873   america  Italian
Japan              127.061   4602367        377930  0.891   america      NaN
United Kingdom      64.511   2950039        242495  0.907   america      NaN
United States      318.523  17348075       9525067  0.915   america      NaN

In [49]:
df.append(pd.Series({
    'Population': 3,
    'GDP': 5
}, name='China'))

C:\Users\91968\AppData\Local\Temp\ipykernel_28336\3683103025.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(pd.Series({

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387     9984670.0  0.913   america      NaN
France              63.951   2833687      640679.0  0.888   america   French
Germany             80.940   3874437      357114.0  0.916   america   German
Italy               60.665   2167744      301336.0  0.873   america  Italian
Japan              127.061   4602367      377930.0  0.891   america      NaN
United Kingdom      64.511   2950039      242495.0  0.907   america      NaN
United States      318.523  17348075     9525067.0  0.915   america      NaN
China                3.000         5           NaN    NaN       NaN      NaN

In [50]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   america      NaN
France              63.951   2833687        640679  0.888   america   French
Germany             80.940   3874437        357114  0.916   america   German
Italy               60.665   2167744        301336  0.873   america  Italian
Japan              127.061   4602367        377930  0.891   america      NaN
United Kingdom      64.511   2950039        242495  0.907   america      NaN
United States      318.523  17348075       9525067  0.915   america      NaN

In [58]:
df['GDP'] / df['Population']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
China                      NaN
dtype: float64

In [59]:
df['GDP Per Capita'] = df['GDP'] / df['Population']

In [60]:
df

,Population,GDP,Surface Area,HDI,Continent,Language,GDP Per Capita
Canada,3.546700e+01,1785387.0,9984670.0,0.913,america,NaN,50339.385908
France,6.395100e+01,2833687.0,640679.0,0.888,america,French,44310.284437
Germany,8.094000e+01,3874437.0,357114.0,0.916,america,German,47868.013343
Italy,6.066500e+01,2167744.0,301336.0,0.873,america,Italian,35733.025633
Japan,1.270610e+02,4602367.0,377930.0,0.891,america,NaN,36221.712406
United Kingdom,6.451100e+01,2950039.0,242495.0,0.907,america,NaN,45729.239975
United States,3.185230e+02,17348075.0,9525067.0,0.915,america,NaN,54464.120330
China,1.400000e+09,NaN,NaN,NaN,Asia,NaN,NaN