In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.isnull(np.nan)

True

In [5]:
pd.isnull(None)

True

In [5]:
pd.isna(np.nan)

True

In [6]:
pd.isna(None)

True

In [7]:
pd.notnull(None)

False

In [8]:

pd.notnull(np.nan)

False

In [9]:
pd.notna(np.nan)

False

In [10]:
pd.notnull(3)

True

In [11]:
pd.isnull(pd.Series([1, np.nan, 7]))

0    False
1     True
2    False
dtype: bool

In [12]:
pd.notnull(pd.Series([1, np.nan, 7]))

0     True
1    False
2     True
dtype: bool

In [13]:
pd.isnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))

   Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

In [14]:

pd.Series([1, 2, np.nan]).count()

2

In [15]:
pd.Series([1, 2, np.nan]).sum()

3.0

In [16]:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])

In [17]:
pd.notnull(s)

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [18]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [19]:
pd.notnull(s).sum()

4

In [20]:
pd.isnull(s).sum()

2

In [21]:
s[pd.notnull(s)]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [22]:

s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [23]:
s.notnull()

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [24]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [25]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [26]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [27]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [28]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [29]:
df.shape

(4, 4)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes

In [31]:
df.isnull()

   Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [32]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [33]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [34]:
df.dropna()

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [35]:
df.dropna(axis=0)

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [36]:
df.dropna(axis=1)

   Column D
0         5
1         8
2        34
3       110

In [37]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})

In [38]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [39]:
df.dropna(how='all')

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [39]:
df.dropna(how='any')  # default behavior

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [40]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [41]:
df.dropna(thresh=3) #i.e.,mini. three valid values

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

In [42]:
df.dropna(thresh=3, axis='columns')

   Column B  Column C  Column D
0       2.0       NaN         5
1       8.0       9.0         8
2      31.0      32.0        34
3       NaN     100.0       110

In [43]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [44]:
#fill = foreward fill , bfill = backward fill , limitation can't substitute values at extremities

In [45]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    0.0
5    4.0
dtype: float64

In [46]:

s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

In [47]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [48]:
s.fillna(method='ffill')

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [49]:
s.fillna(method='bfill')

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

In [50]:
#This can still leave null values at the extremes of the Series/DataFrame:

In [51]:
pd.Series([np.nan, 3, np.nan, 9]).fillna(method='ffill')

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [52]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).fillna(method='bfill')

0    1.0
1    3.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [53]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [54]:
df.fillna({'Column A': 0, 'Column B': 99, 'Column C': df['Column C'].mean()})

   Column A  Column B  Column C  Column D
0       1.0       2.0      47.0         5
1       0.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3       0.0      99.0     100.0       110

In [55]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [ ]:
#axis =0 means column wise and vice versa

In [56]:
df.fillna(method='ffill', axis=0)

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       1.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3      30.0      31.0     100.0       110

In [57]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [58]:
df.fillna(method='ffill', axis=1)

   Column A  Column B  Column C  Column D
0       1.0       2.0       2.0       5.0
1       NaN       8.0       9.0       8.0
2      30.0      31.0      32.0      34.0
3       NaN       NaN     100.0     110.0

In [65]:
s.dropna().count()

4

In [66]:
missing_values = len(s.dropna()) != len(s)
missing_values

True

In [67]:
len(s)

6

In [68]:
s.count()

4

In [69]:
missing_values = s.count() != len(s)
missing_values

True

In [70]:
pd.Series([True, False, False]).any()

True

In [71]:
pd.Series([True, False, False]).all()

False

In [72]:
pd.Series([True, True, True]).all()

True

In [73]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [75]:
pd.Series([1, np.nan]).isnull().any()

True

In [76]:
pd.Series([1, 2]).isnull().any()

False

In [77]:
s.isnull().any()

True

In [78]:

s.isnull().values

array([False, False, False,  True,  True, False])

In [80]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [79]:

df.isnull().values

array([[False, False,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True,  True, False, False]])

In [81]:
s.isnull().values.any()

True