In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Data_Model_Creation\Practice_file.csv")
df.head(5)

,Cust ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Date of Birth,SSN,...,City,Zip,Product Name,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price
0,C-973342,Mr.,Nickolas,V,Lara,M,nickolas.lara@hotmail.com,Elliott Lara,24-03-1992,419-67-3843,...,Huslia,99746,P-VG-022,Offline,M,17-10-2015,VG-022_4229433687_AK22,17-10-2015,22,118.209
1,C-880500,Mrs.,Lahoma,S,Lachance,F,lahoma.lachance@microsoft.com,Marco Lachance,05-02-1990,534-71-6211,...,Skagway,99840,P-BV-002,Online,H,12-11-2016,BV-002_4268632909_AK110,20-11-2016,71,41.327
2,C-439016,Dr.,Franklin,M,Rutter,M,franklin.rutter@gmail.com,Abel Rutter,11-02-1996,352-08-1915,...,Thorne Bay,99919,P-CT-003,Offline,L,24-07-2018,CT-003_4330535106_AK71,24-07-2018,43,46.592
3,C-635735,Ms.,Cathryn,F,Durham,F,cathryn.durham@shell.com,Antwan Durham,05-02-1971,552-99-1456,...,Nunapitchuk,99641,P-CR-003,Offline,L,03-02-2016,CR-003_4240325969_AK1,03-02-2016,51,152.243
4,C-213274,Ms.,Verda,K,Oswalt,F,verda.oswalt@gmail.com,Demetrius Oswalt,09-10-1977,657-36-0554,...,Homer,99603,P-BF-002,Offline,H,24-01-2016,BF-002_4239328407_AK70,24-01-2016,71,207.246

In [8]:
print(df.columns.tolist())

['Cust ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name', 'Gender', 'E Mail', "Father's Name", 'Date of Birth', 'SSN', 'Phone No. ', 'Region', 'State', 'City', 'Zip', 'Product Name', 'Sales Channel', 'Order Priority', 'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price']

In [9]:
df.columns = [

    col.strip()
       .lower()
       .replace(' ', '_')
       .replace('.', '')
       .replace("'", '')
    
    for col in df.columns

]

print(df.columns.tolist())

['cust_id', 'name_prefix', 'first_name', 'middle_initial', 'last_name', 'gender', 'e_mail', 'fathers_name', 'date_of_birth', 'ssn', 'phone_no', 'region', 'state', 'city', 'zip', 'product_name', 'sales_channel', 'order_priority', 'order_date', 'order_id', 'ship_date', 'units_sold', 'unit_price']

In [10]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'])

C:\Users\91968\AppData\Local\Temp\ipykernel_16720\822221969.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['order_date'] = pd.to_datetime(df['order_date'])
C:\Users\91968\AppData\Local\Temp\ipykernel_16720\822221969.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['ship_date'] = pd.to_datetime(df['ship_date'])
C:\Users\91968\AppData\Local\Temp\ipykernel_16720\822221969.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date_of_birth'] = pd.to_datetime(df['date_of_birth'])

In [11]:
dim_customer = df[[

    'cust_id',
    'name_prefix',
    'first_name',
    'middle_initial',
    'last_name',
    'gender',
    'e_mail',
    'fathers_name',
    'date_of_birth',
    'ssn',
    'phone_no'

]].drop_duplicates().reset_index(drop=True)

In [14]:
dim_customer['customer_key'] = range( 1, len(dim_customer)+1 ) 
dim_customer.head()

,cust_id,name_prefix,first_name,middle_initial,last_name,gender,e_mail,fathers_name,date_of_birth,ssn,phone_no,customer_key
0,C-973342,Mr.,Nickolas,V,Lara,M,nickolas.lara@hotmail.com,Elliott Lara,1992-03-24,419-67-3843,907-531-8626,1
1,C-880500,Mrs.,Lahoma,S,Lachance,F,lahoma.lachance@microsoft.com,Marco Lachance,1990-02-05,534-71-6211,907-273-2588,2
2,C-439016,Dr.,Franklin,M,Rutter,M,franklin.rutter@gmail.com,Abel Rutter,1996-02-11,352-08-1915,907-878-1037,3
3,C-635735,Ms.,Cathryn,F,Durham,F,cathryn.durham@shell.com,Antwan Durham,1971-02-05,552-99-1456,907-641-5776,4
4,C-213274,Ms.,Verda,K,Oswalt,F,verda.oswalt@gmail.com,Demetrius Oswalt,1977-10-09,657-36-0554,907-513-4651,5

In [12]:
dim_location = df[[

    'region',
    'state',
    'city',
    'zip'

]].drop_duplicates().reset_index(drop=True)

In [15]:
dim_location['location_key'] = range( 1, len(dim_location)+1 ) 
dim_location.head()

  region state         city    zip  location_key
0   West    AK       Huslia  99746             1
1   West    AK      Skagway  99840             2
2   West    AK   Thorne Bay  99919             3
3   West    AK  Nunapitchuk  99641             4
4   West    AK        Homer  99603             5

In [16]:
dim_product = df[[ 'product_name' ]].drop_duplicates().reset_index(drop=True)

In [17]:
dim_product['product_key'] = range( 1, len(dim_product)+1 ) 
dim_product.head()

  product_name  product_key
0     P-VG-022            1
1     P-BV-002            2
2     P-CT-003            3
3     P-CR-003            4
4     P-BF-002            5

In [18]:
all_dates = pd.concat([ df['order_date'], df['ship_date'] ]).drop_duplicates()

In [19]:
dim_date = pd.DataFrame({ 'full_date': all_dates })

In [21]:
dim_date['date_key'] = dim_date[ 'full_date' ].dt.strftime('%Y%m%d').astype(int) 
dim_date['year'] = dim_date[ 'full_date' ].dt.year 
dim_date['month'] = dim_date[ 'full_date' ].dt.month 
dim_date['day'] = dim_date[ 'full_date' ].dt.day 
dim_date['weekday'] = dim_date[ 'full_date' ].dt.day_name() 
dim_date['quarter'] = dim_date[ 'full_date' ].dt.quarter

In [22]:
dim_date.head()

   full_date  date_key  year  month  day    weekday  quarter
0 2015-10-17  20151017  2015     10   17   Saturday        4
1 2016-11-12  20161112  2016     11   12   Saturday        4
2 2018-07-24  20180724  2018      7   24    Tuesday        3
3 2016-02-03  20160203  2016      2    3  Wednesday        1
4 2016-01-24  20160124  2016      1   24     Sunday        1

In [23]:
fact_sales = df.copy()

In [24]:
fact_sales = fact_sales.merge( dim_customer[ ['cust_id', 'customer_key'] ], on='cust_id', how='left' )

In [25]:
fact_sales = fact_sales.merge( dim_product[ ['product_name', 'product_key'] ], on='product_name', how='left' )

In [26]:
fact_sales = fact_sales.merge( dim_location[ [ 'region', 'state', 'city', 'zip', 'location_key' ] ], on=[ 'region', 'state', 'city', 'zip' ], how='left' )

In [27]:
fact_sales['order_date_key'] = fact_sales[ 'order_date' ].dt.strftime('%Y%m%d').astype(int)

In [28]:
fact_sales['ship_date_key'] = fact_sales[ 'ship_date' ].dt.strftime('%Y%m%d').astype(int)

In [29]:
fact_sales['total_sales'] = ( fact_sales['units_sold'] * fact_sales['unit_price'] )

In [30]:
fact_sales = fact_sales[[ 'order_id', 'customer_key', 'product_key', 'location_key', 'order_date_key', 'ship_date_key', 'units_sold', 'unit_price', 'total_sales' ]]

In [31]:
fact_sales['sales_key'] = range( 1, len(fact_sales)+1 )

In [33]:
fact_sales = fact_sales[[ 'sales_key', 'order_id', 'customer_key', 'product_key', 'location_key', 'order_date_key', 'ship_date_key', 'units_sold', 'unit_price', 'total_sales' ]] 
fact_sales.head()

,sales_key,order_id,customer_key,product_key,location_key,order_date_key,ship_date_key,units_sold,unit_price,total_sales
0,1,VG-022_4229433687_AK22,1,1,1,20151017,20151017,22,118.209,2600.598
1,2,BV-002_4268632909_AK110,2,2,2,20161112,20161120,71,41.327,2934.217
2,3,CT-003_4330535106_AK71,3,3,3,20180724,20180724,43,46.592,2003.456
3,4,CR-003_4240325969_AK1,4,4,4,20160203,20160203,51,152.243,7764.393
4,5,BF-002_4239328407_AK70,5,5,5,20160124,20160124,71,207.246,14714.466

In [37]:
print('\nDIM CUSTOMER')
print(dim_customer.head())

print('\nDIM LOCATION')
print(dim_location.head())

print('\nDIM PRODUCT')
print(dim_product.head())

print('\nDIM DATE')
print(dim_date.head())

print('\nFACT SALES')
print(fact_sales.head())

DIM CUSTOMER
    cust_id name_prefix first_name middle_initial last_name gender  \
0  C-973342         Mr.   Nickolas              V      Lara      M
1  C-880500        Mrs.     Lahoma              S  Lachance      F
2  C-439016         Dr.   Franklin              M    Rutter      M
3  C-635735         Ms.    Cathryn              F    Durham      F
4  C-213274         Ms.      Verda              K    Oswalt      F

                          e_mail      fathers_name date_of_birth          ssn  \
0      nickolas.lara@hotmail.com      Elliott Lara    1992-03-24  419-67-3843
1  lahoma.lachance@microsoft.com    Marco Lachance    1990-02-05  534-71-6211
2      franklin.rutter@gmail.com       Abel Rutter    1996-02-11  352-08-1915
3       cathryn.durham@shell.com     Antwan Durham    1971-02-05  552-99-1456
4         verda.oswalt@gmail.com  Demetrius Oswalt    1977-10-09  657-36-0554

       phone_no  customer_key
0  907-531-8626             1
1  907-273-2588             2
2  907-878-1037             3
3  907-641-5776             4
4  907-513-4651             5

DIM LOCATION
  region state         city    zip  location_key
0   West    AK       Huslia  99746             1
1   West    AK      Skagway  99840             2
2   West    AK   Thorne Bay  99919             3
3   West    AK  Nunapitchuk  99641             4
4   West    AK        Homer  99603             5

DIM PRODUCT
  product_name  product_key
0     P-VG-022            1
1     P-BV-002            2
2     P-CT-003            3
3     P-CR-003            4
4     P-BF-002            5

DIM DATE
   full_date  date_key  year  month  day    weekday  quarter
0 2015-10-17  20151017  2015     10   17   Saturday        4
1 2016-11-12  20161112  2016     11   12   Saturday        4
2 2018-07-24  20180724  2018      7   24    Tuesday        3
3 2016-02-03  20160203  2016      2    3  Wednesday        1
4 2016-01-24  20160124  2016      1   24     Sunday        1

FACT SALES
   sales_key                 order_id  customer_key  product_key  \
0          1   VG-022_4229433687_AK22             1            1
1          2  BV-002_4268632909_AK110             2            2
2          3   CT-003_4330535106_AK71             3            3
3          4    CR-003_4240325969_AK1             4            4
4          5   BF-002_4239328407_AK70             5            5

   location_key  order_date_key  ship_date_key  units_sold  unit_price  \
0             1        20151017       20151017          22     118.209
1             2        20161112       20161120          71      41.327
2             3        20180724       20180724          43      46.592
3             4        20160203       20160203          51     152.243
4             5        20160124       20160124          71     207.246

   total_sales
0     2600.598
1     2934.217
2     2003.456
3     7764.393
4    14714.466

In [38]:
# Save DIM tables

dim_customer.to_csv(
    r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Data_Model_Creation\Model_Tables\dim_customer.csv",
    index=False
)

dim_location.to_csv(
    r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Data_Model_Creation\Model_Tables\dim_location.csv",
    index=False
)

dim_product.to_csv(
    r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Data_Model_Creation\Model_Tables\dim_product.csv",
    index=False
)

dim_date.to_csv(
    r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Data_Model_Creation\Model_Tables\dim_date.csv",
    index=False
)

# Save FACT table

fact_sales.to_csv(
    r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Data_Model_Creation\Model_Tables\fact_sales.csv",
    index=False
)

print("All files saved successfully")

All files saved successfully