In [1]:
import numpy as np
import pandas as pd

In [2]:

S_Date1 = '2026-05-05 00:00:00'
E_Date1 = '2026-05-11 23:59:59'

#For Autoapproved jobs
S_Date2 = '2026-05-06 00:00:00'
E_Date2 = '2026-05-12 23:59:59'

Raw_data_path = r"C:\Gaurav\US Reconcillation\2026\May'26\5 May'26 - 11 May'26\Raw\Closed_Case_–_Activity_Invoices_–_Activity (5).xlsx"
WD_Files_path = r"C:\Gaurav\US Reconcillation\2026\May'26\5 May'26 - 11 May'26\Combine\Combine_Final_25.xlsx"
Prev_WD_Files_path = r"C:\Gaurav\US Reconcillation\2026\April'26\28 April - 4 May\Working\US Working 28 April'26 - 4 May'26 (Run 06 April'26 - 07 May'26 ).xlsx"
Output_path = r"C:\\Gaurav\\US Reconcillation\\2026\\May'26\\5 May'26 - 11 May'26\\Upload\\Final_Detailed.xlsx"

In [3]:

raw_data = pd.read_excel(Raw_data_path)
raw_data

,Activity Invoice Report,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
2,184004394,Tante Brianna,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
3,184002562,Canning Katelyn,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184046213,Tarleton State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
4,184001209,Exyt Latasha,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9317,184001227,Smith Shilain,Employee Full-Time,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184028608,State Farm Mutual Automobile Insurance Company...,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9318,26645,Wheeler Kim,Employee Full-Time,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184028693,"Airgas, Inc.",...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9319,184000364,Anderson-White Deirdre,Employee Part-Time,NaN,1,No,UNITED STATES OF AMERICA,GEORGIA,184054855,City of Owatonna,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9320,184001008,Choudry Faryal,Employee Full-Time,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184019863,Dan & Jerry's Greenhouse Inc. - Metlife Grief...,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9321,184000499,Waples Kimmy,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184054141,"Texas A&M University, Corpus Christi - Student",...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN

In [4]:
data1 = raw_data.copy()
data1

,Activity Invoice Report,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
2,184004394,Tante Brianna,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
3,184002562,Canning Katelyn,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184046213,Tarleton State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
4,184001209,Exyt Latasha,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9317,184001227,Smith Shilain,Employee Full-Time,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184028608,State Farm Mutual Automobile Insurance Company...,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9318,26645,Wheeler Kim,Employee Full-Time,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184028693,"Airgas, Inc.",...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9319,184000364,Anderson-White Deirdre,Employee Part-Time,NaN,1,No,UNITED STATES OF AMERICA,GEORGIA,184054855,City of Owatonna,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9320,184001008,Choudry Faryal,Employee Full-Time,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184019863,Dan & Jerry's Greenhouse Inc. - Metlife Grief...,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN
9321,184000499,Waples Kimmy,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184054141,"Texas A&M University, Corpus Christi - Student",...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN

In [5]:
data1 = data1.drop(data1.index[:1])
data1 = data1.reset_index(drop=True)
data1.head()

,Activity Invoice Report,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
1,184004394,Tante Brianna,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
2,184002562,Canning Katelyn,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184046213,Tarleton State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
3,184001209,Exyt Latasha,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
4,184004392,Redman Althea,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184045551,University of Rhode Island - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN

In [6]:
data1.columns = data1.iloc[0]

In [7]:
data1.head()

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
0,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
1,184004394,Tante Brianna,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
2,184002562,Canning Katelyn,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184046213,Tarleton State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
3,184001209,Exyt Latasha,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
4,184004392,Redman Althea,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184045551,University of Rhode Island - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN

In [8]:
data1 = data1.drop(data1.index[0])
data1.head()

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
1,184004394,Tante Brianna,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
2,184002562,Canning Katelyn,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184046213,Tarleton State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
3,184001209,Exyt Latasha,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
4,184004392,Redman Althea,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184045551,University of Rhode Island - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
5,184004392,Redman Althea,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184045931,Texas Tech University - Student,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN

In [9]:
data1 = data1.reset_index(drop=True)
data1.head()

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
0,184004394,Tante Brianna,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
1,184002562,Canning Katelyn,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,184046213,Tarleton State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
2,184001209,Exyt Latasha,NaN,NaN,1,No,UNITED STATES OF AMERICA,ILLINOIS,1139349,Arizona State University - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
3,184004392,Redman Althea,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184045551,University of Rhode Island - Student,...,0,CAD,0,0,0,NaN,Symphoni,NaN,NaN,NaN
4,184004392,Redman Althea,NaN,NaN,1,No,UNITED STATES OF AMERICA,TEXAS,184045931,Texas Tech University - Student,...,0,CAD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN

In [10]:
filtered_data1 = data1[data1['Vendor ID'] != 1]
filtered_data1.head()

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
16,13168,Hecht Marion,Contractor (Affiliated Provider),230865,1758,Yes,UNITED STATES OF AMERICA,NEW JERSEY,184053749,Western Governors University Corporation,...,78,USD,0,0,78,NaN,LifeWorks-US,NaN,NaN,NaN
19,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
22,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
25,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
31,11830,Babbitt Claire,Contractor (Affiliated Provider),234357,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184027054,Garden Grove Unified School District GGUSD- Me...,...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN

In [11]:
filtered_data1.head()

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
16,13168,Hecht Marion,Contractor (Affiliated Provider),230865,1758,Yes,UNITED STATES OF AMERICA,NEW JERSEY,184053749,Western Governors University Corporation,...,78,USD,0,0,78,NaN,LifeWorks-US,NaN,NaN,NaN
19,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
22,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
25,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
31,11830,Babbitt Claire,Contractor (Affiliated Provider),234357,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184027054,Garden Grove Unified School District GGUSD- Me...,...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN

In [12]:
filtered_data1 = filtered_data1.reset_index(drop=True)
filtered_data1

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,...,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
0,13168,Hecht Marion,Contractor (Affiliated Provider),230865,1758,Yes,UNITED STATES OF AMERICA,NEW JERSEY,184053749,Western Governors University Corporation,...,78,USD,0,0,78,NaN,LifeWorks-US,NaN,NaN,NaN
1,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
2,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
3,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
4,11830,Babbitt Claire,Contractor (Affiliated Provider),234357,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184027054,Garden Grove Unified School District GGUSD- Me...,...,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,4032,Continuum R3,Contractor (Affiliated Provider),236307,409,Yes,UNITED STATES OF AMERICA,MICHIGAN,184026161,Resourcing Edge I LLC,...,310,USD,25,0,335,US Trauma KW,LifeWorks-US,NaN,NaN,NaN
969,4032,Continuum R3,Contractor (Affiliated Provider),236307,409,Yes,UNITED STATES OF AMERICA,MICHIGAN,184027446,Gate Group,...,1240,USD,165,0,1405,US Trauma KW,Symphoni,NaN,NaN,NaN
970,4032,Continuum R3,Contractor (Affiliated Provider),236307,409,Yes,UNITED STATES OF AMERICA,MICHIGAN,184055639,Trucordia,...,540,USD,165,0,705,US Trauma KW,LifeWorks-US,NaN,NaN,NaN
971,8847,Schirg Ralf,Contractor (Affiliated Provider),129754,4602,Yes,UNITED STATES OF AMERICA,MINNESOTA,184055635,Kimberly-Clark Corporation,...,200,USD,0,0,200,KG,Symphoni,NaN,NaN,NaN
972,22851,Canepa Patricia,Contractor (Affiliated Provider),331842,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184038120,Valley First Credit Union,...,90,USD,0,0,90,NaN,Symphoni,NaN,NaN,NaN

In [13]:
filtered_data1.shape

(973, 65)

In [14]:
filtered_data1.columns

Index(['Provider ID', 'Provider Name', 'Employment Type', 'Supplier ID',
       'Vendor ID', 'Pay Vendor Directly (Y/N)?', 'Provider Country',
       'Provider  Province/State', 'Org ID', 'Org Name', 'Renewal Date',
       'Max hours for contract period', 'Provider Email Type', 'Model Number',
       'Fee Type', 'Case ID', 'Activity ID', 'Activity Opened Date',
       'Activity Status', 'Service Code', 'Modality', 'Invoice ID',
       'Invoice Status', 'Invoice Approval Date', 'Approver Name',
       'Provider Invoice Number', 'Invoice Created Date', 'Created by',
       'Export Date', 'Regular Rate Fee', 'Regular Rate Type',
       'Regular Rate Billable \nHours', 'Regular Rate Non-Billable \nHours',
       'No Show \nFee', 'No Show \nType', 'No Show Billable\nHours',
       'No Show Non-Billable\nHours', 'Case Management Fee',
       'Case Management Type', 'Case Management Billble Hours',
       'Case Management Non-Billble Hours', 'Special Rate Fee',
       'Special Rate Type', 'Special Rate Billable\nHours',
       'Special Rate Non-Billable\nHours', 'Other \nBillable\nHours',
       'Other \nNon-Billable\nHours', 'Staff\nBillable\n Hours',
       'Staff\nNon-Billable\n Hours', 'Total \nBillable\nHours',
       'Total \nNon-Billable\nHours', 'Total \nPayable\nHours',
       'Total \nNon-Payable\nHours', 'Total Hours', 'Taxes', 'Total Invoice',
       'Currency', 'Expenses Payable', 'Expenses  non Payable',
       'Total Payable', 'Comment', 'Source', 'Taxes: Province/State',
       'Tax Type', 'Tax Account Number'],
      dtype='object', name=0)

In [15]:
pd.set_option('display.max_columns', None)
filtered_data1.head(2)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
0,13168,Hecht Marion,Contractor (Affiliated Provider),230865,1758,Yes,UNITED STATES OF AMERICA,NEW JERSEY,184053749,Western Governors University Corporation,2025-12-01 00:00:00,NaN,NaN,3,Per Employee Per Month,184909531,185356924,2026-03-30 06:21:27.567000,Active,ST2,In Person,185310836,Approved,2026-04-14 00:00:00,AutoApprovalJob,NaN,2026-04-12 09:09:46.703000,13168,2026-04-14 00:30:40.053000,78,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,78,USD,0,0,78,NaN,LifeWorks-US,NaN,NaN,NaN
1,467,Vyzas Ben,Contractor (Affiliated Provider),34348,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184905926,185356602,2026-03-27 13:17:02.140000,Active,ST,In Person,185310839,Approved,2026-04-14 00:00:00,AutoApprovalJob,NaN,2026-04-12 10:15:50.477000,467,2026-04-14 00:30:40.130000,75,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,75,USD,0,0,75,NaN,LifeWorks-US,NaN,NaN,NaN

In [16]:
filtered_data1['Created by'].unique()

array(['13168', '467', '11830', '495083', 'Kajal Garg', '18417',
       'Vanshika Sachdeva', '184004513', '184004096', '496766', '21695',
       '13568', '184000058', '18811', '184001553', '184004512',
       '184003705', '13523', 'Vilma Papillon', '184002965', '184002830',
       '184002574', '499959', '26575', '495688', '14709', '184004023',
       '184002195', '184000538', '497244', '184002825', '13707', '19321',
       'Kimberly Winters', '184004152', '19507', '499943', '184000053',
       '184000234', '24232', '13105', '12401', '184003704', '184000884',
       '184002172', '184004496', '12383', '25416', '13987', '184002895',
       '18329', '22614', '14624', '15014', '19113', '22366',
       '184004457  ', '184003857', '184004438', '184004115', '184003969',
       '494985', '12639', '495326', '22339', '11905', '184002373',
       '499900', '499851', '12849', '184003985', '184004410',
       'Sweta Vanker', '13961', '15248', '13703', '184000061',
       '184004468', '184003972', '184003967', '496136', '184003755',
       '18158', '184000605', '184003120', '184000228', '184000686',
       '184001095', '184001849', '496796', '14157', '14531', '15931',
       '184001878', '184004571', '17776', '16938', '22813', '19194',
       '184000822', '13861', '14904', '184003084', '14109', '496687',
       '12561', '184003812', '14179', '184000707', '184000074', '13252',
       '4660', '184002178', 'Darpan Lnu', '184000865', '184002514',
       '184003979', '23275', '25429', '184004603', '15558', '184004677',
       '184001983', '14280', '23497', '184003358', '20263', '13570',
       '12149', '184004451', '23463', '184002356', '184004092', ' 497897',
       '184004210', '184002565', '184000099', '184003011', '184004017',
       '497552', '184002395', '21611', '184002813', '184003859', '499466',
       '184002270', '18235', '497190', '12200', '184001065', '184004220',
       '12453', '13939', '495959', '15424', '184000977', '15055', '13793',
       '22486', '184002943', '495299', '12854', '184004684', '184001581',
       '14395', '184003298', '184003586', '184000919', '16593',
       '184002864', '25189', '184001921', '184001146', '12211', '495945',
       '184004132', '14777', '496936', '495228', '18355', '13788',
       '21368', '496702', '495707', '184003771', '496527', '13340',
       'WSPBilling', 'Neha Saini', '25451', '184001241', '184003274',
       '22841', 'carmstrong', '184004424', '184004315', '184000341',
       '495292', '184004402', '15948', '184002891', '184004526',
       '184000873', '184000988', '13776', '14134', '184004563', '495219',
       '184002810', '12569', 'Ayushi Lnu', '497892', ' 184002471',
       '184001834', '15847', '184000127', '184004385 ', '23812', '495984',
       '184004573', '184004716', '24294', '19325', '20049', '15659',
       '497520', '14073', '16748', '14600', '22397', '11885', '184001712',
       '184001970', '184003986', '496654', '495238', '184003196 ',
       '14833', '184003777', '498479', '16419', '11784', '29040',
       '497758', '22056', '184003959', '16954', '16533', '184003494',
       '184002042', '184002023', '184003839', '184002875', '184002958'],
      dtype=object)

In [17]:
filtered_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 65 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provider ID                        973 non-null    object
 1   Provider Name                      973 non-null    object
 2   Employment Type                    962 non-null    object
 3   Supplier ID                        951 non-null    object
 4   Vendor ID                          671 non-null    object
 5   Pay Vendor Directly (Y/N)?         973 non-null    object
 6   Provider Country                   973 non-null    object
 7   Provider  Province/State           973 non-null    object
 8   Org ID                             973 non-null    object
 9   Org Name                           973 non-null    object
 10  Renewal Date                       973 non-null    object
 11  Max hours for contract period      3 non-null      object
 12  Provider Email Type                9 non-null      object
 13  Model Number                       942 non-null    object
 14  Fee Type                           960 non-null    object
 15  Case ID                            973 non-null    object
 16  Activity ID                        973 non-null    object
 17  Activity Opened Date               973 non-null    object
 18  Activity Status                    973 non-null    object
 19  Service Code                       973 non-null    object
 20  Modality                           973 non-null    object
 21  Invoice ID                         973 non-null    object
 22  Invoice Status                     973 non-null    object
 23  Invoice Approval Date              642 non-null    object
 24  Approver Name                      642 non-null    object
 25  Provider Invoice Number            417 non-null    object
 26  Invoice Created Date               973 non-null    object
 27  Created by                         973 non-null    object
 28  Export Date                        893 non-null    object
 29  Regular Rate Fee                   973 non-null    object
 30  Regular Rate Type                  885 non-null    object
 31  Regular Rate Billable
Hours       795 non-null    object
 32  Regular Rate Non-Billable
Hours   90 non-null     object
 33  No Show
Fee                       955 non-null    object
 34  No Show
Type                      1 non-null      object
 35  No Show Billable
Hours             1 non-null      object
 36  No Show Non-Billable
Hours         0 non-null      object
 37  Case Management Fee                955 non-null    object
 38  Case Management Type               2 non-null      object
 39  Case Management Billble Hours      0 non-null      object
 40  Case Management Non-Billble Hours  2 non-null      object
 41  Special Rate Fee                   955 non-null    object
 42  Special Rate Type                  68 non-null     object
 43  Special Rate Billable
Hours        58 non-null     object
 44  Special Rate Non-Billable
Hours    10 non-null     object
 45  Other
Billable
Hours              0 non-null      object
 46  Other
Non-Billable
Hours          0 non-null      object
 47  Staff
Billable
 Hours              1 non-null      object
 48  Staff
Non-Billable
 Hours          0 non-null      object
 49  Total
Billable
Hours              973 non-null    object
 50  Total
Non-Billable
Hours          973 non-null    object
 51  Total
Payable
Hours               973 non-null    object
 52  Total
Non-Payable
Hours           973 non-null    object
 53  Total Hours                        973 non-null    object
 54  Taxes                              955 non-null    object
 55  Total Invoice                      973 non-null    object
 56  Currency                           973 non-null    object
 57  Expenses Payable                   955 non-null    object
 58  Expenses  non Payable              955 non-null    object
 59  Total Payable                      973 non-null    object
 60  Comment                            216 non-null    object
 61  Source                             973 non-null    object
 62  Taxes: Province/State              31 non-null     object
 63  Tax Type                           31 non-null     object
 64  Tax Account Number                 31 non-null     object
dtypes: object(65)
memory usage: 494.2+ KB

In [18]:
filtered_data1['Invoice Created Date'] = pd.to_datetime(filtered_data1['Invoice Created Date'], errors='coerce')
filtered_data1['Invoice Approval Date'] = pd.to_datetime(filtered_data1['Invoice Approval Date'], errors='coerce')

In [19]:
filtered_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 65 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provider ID                        973 non-null    object
 1   Provider Name                      973 non-null    object
 2   Employment Type                    962 non-null    object
 3   Supplier ID                        951 non-null    object
 4   Vendor ID                          671 non-null    object
 5   Pay Vendor Directly (Y/N)?         973 non-null    object
 6   Provider Country                   973 non-null    object
 7   Provider  Province/State           973 non-null    object
 8   Org ID                             973 non-null    object
 9   Org Name                           973 non-null    object
 10  Renewal Date                       973 non-null    object
 11  Max hours for contract period      3 non-null      object
 12  Provider Email Type                9 non-null      object
 13  Model Number                       942 non-null    object
 14  Fee Type                           960 non-null    object
 15  Case ID                            973 non-null    object
 16  Activity ID                        973 non-null    object
 17  Activity Opened Date               973 non-null    object
 18  Activity Status                    973 non-null    object
 19  Service Code                       973 non-null    object
 20  Modality                           973 non-null    object
 21  Invoice ID                         973 non-null    object
 22  Invoice Status                     973 non-null    object
 23  Invoice Approval Date              642 non-null    datetime64[ns]
 24  Approver Name                      642 non-null    object
 25  Provider Invoice Number            417 non-null    object
 26  Invoice Created Date               973 non-null    datetime64[ns]
 27  Created by                         973 non-null    object
 28  Export Date                        893 non-null    object
 29  Regular Rate Fee                   973 non-null    object
 30  Regular Rate Type                  885 non-null    object
 31  Regular Rate Billable
Hours       795 non-null    object
 32  Regular Rate Non-Billable
Hours   90 non-null     object
 33  No Show
Fee                       955 non-null    object
 34  No Show
Type                      1 non-null      object
 35  No Show Billable
Hours             1 non-null      object
 36  No Show Non-Billable
Hours         0 non-null      object
 37  Case Management Fee                955 non-null    object
 38  Case Management Type               2 non-null      object
 39  Case Management Billble Hours      0 non-null      object
 40  Case Management Non-Billble Hours  2 non-null      object
 41  Special Rate Fee                   955 non-null    object
 42  Special Rate Type                  68 non-null     object
 43  Special Rate Billable
Hours        58 non-null     object
 44  Special Rate Non-Billable
Hours    10 non-null     object
 45  Other
Billable
Hours              0 non-null      object
 46  Other
Non-Billable
Hours          0 non-null      object
 47  Staff
Billable
 Hours              1 non-null      object
 48  Staff
Non-Billable
 Hours          0 non-null      object
 49  Total
Billable
Hours              973 non-null    object
 50  Total
Non-Billable
Hours          973 non-null    object
 51  Total
Payable
Hours               973 non-null    object
 52  Total
Non-Payable
Hours           973 non-null    object
 53  Total Hours                        973 non-null    object
 54  Taxes                              955 non-null    object
 55  Total Invoice                      973 non-null    object
 56  Currency                           973 non-null    object
 57  Expenses Payable                   955 non-null    object
 58  Expenses  non Payable              955 non-null    object
 59  Total Payable                      973 non-null    object
 60  Comment                            216 non-null    object
 61  Source                             973 non-null    object
 62  Taxes: Province/State              31 non-null     object
 63  Tax Type                           31 non-null     object
 64  Tax Account Number                 31 non-null     object
dtypes: datetime64[ns](2), object(63)
memory usage: 494.2+ KB

In [20]:
sorted_values = filtered_data1['Created by'].unique()
sorted_values.sort()
print(sorted_values)

[' 184002471' ' 497897' '11784' '11830' '11885' '11905' '12149' '12200'
 '12211' '12383' '12401' '12453' '12561' '12569' '12639' '12849' '12854'
 '13105' '13168' '13252' '13340' '13523' '13568' '13570' '13703' '13707'
 '13776' '13788' '13793' '13861' '13939' '13961' '13987' '14073' '14109'
 '14134' '14157' '14179' '14280' '14395' '14531' '14600' '14624' '14709'
 '14777' '14833' '14904' '15014' '15055' '15248' '15424' '15558' '15659'
 '15847' '15931' '15948' '16419' '16533' '16593' '16748' '16938' '16954'
 '17776' '18158' '18235' '18329' '18355' '184000053' '184000058'
 '184000061' '184000074' '184000099' '184000127' '184000228' '184000234'
 '184000341' '184000538' '184000605' '184000686' '184000707' '184000822'
 '184000865' '184000873' '184000884' '184000919' '184000977' '184000988'
 '184001065' '184001095' '184001146' '184001241' '184001553' '184001581'
 '184001712' '184001834' '184001849' '184001878' '184001921' '184001970'
 '184001983' '184002023' '184002042' '184002172' '184002178' '184002195'
 '184002270' '184002356' '184002373' '184002395' '184002514' '184002565'
 '184002574' '184002810' '184002813' '184002825' '184002830' '184002864'
 '184002875' '184002891' '184002895' '184002943' '184002958' '184002965'
 '184003011' '184003084' '184003120' '184003196 ' '184003274' '184003298'
 '184003358' '184003494' '184003586' '184003704' '184003705' '184003755'
 '184003771' '184003777' '184003812' '184003839' '184003857' '184003859'
 '184003959' '184003967' '184003969' '184003972' '184003979' '184003985'
 '184003986' '184004017' '184004023' '184004092' '184004096' '184004115'
 '184004132' '184004152' '184004210' '184004220' '184004315' '184004385 '
 '184004402' '184004410' '184004424' '184004438' '184004451' '184004457  '
 '184004468' '184004496' '184004512' '184004513' '184004526' '184004563'
 '184004571' '184004573' '184004603' '184004677' '184004684' '184004716'
 '18417' '18811' '19113' '19194' '19321' '19325' '19507' '20049' '20263'
 '21368' '21611' '21695' '22056' '22339' '22366' '22397' '22486' '22614'
 '22813' '22841' '23275' '23463' '23497' '23812' '24232' '24294' '25189'
 '25416' '25429' '25451' '26575' '29040' '4660' '467' '494985' '495083'
 '495219' '495228' '495238' '495292' '495299' '495326' '495688' '495707'
 '495945' '495959' '495984' '496136' '496527' '496654' '496687' '496702'
 '496766' '496796' '496936' '497190' '497244' '497520' '497552' '497758'
 '497892' '498479' '499466' '499851' '499900' '499943' '499959'
 'Ayushi Lnu' 'Darpan Lnu' 'Kajal Garg' 'Kimberly Winters' 'Neha Saini'
 'Sweta Vanker' 'Vanshika Sachdeva' 'Vilma Papillon' 'WSPBilling'
 'carmstrong']

In [21]:
# Find non-integer values
numeric_values = pd.to_numeric(filtered_data1['Created by'], errors='coerce')
non_int_mask = numeric_values.isna() & filtered_data1['Created by'].notna()

# Get rows with non-integer values
non_integer_rows = filtered_data1[non_int_mask]
created_by_names = non_integer_rows['Created by'].unique()

print(created_by_names)

['Kajal Garg' 'Vanshika Sachdeva' 'Vilma Papillon' 'Kimberly Winters'
 'Sweta Vanker' 'Darpan Lnu' 'WSPBilling' 'Neha Saini' 'carmstrong'
 'Ayushi Lnu']

In [22]:
filter1 = filtered_data1['Created by'].isin(created_by_names)

start_date1 = S_Date1
end_date1 = E_Date1

filter2 = (filtered_data1['Invoice Created Date'] >= start_date1) & (filtered_data1['Invoice Created Date'] <= end_date1)

filtered_data2 = filtered_data1[filter1 & filter2]

filtered_data2.head(2)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
687,498335,Garnham Steven,Contractor (Affiliated Provider),419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184909998,185356976,2026-03-30 10:34:37.110000,Closed,SA,Video-Counselling,185317458,Approved,NaT,NaN,NaN,2026-05-05 03:14:10.037,Vanshika Sachdeva,2026-05-06 00:30:53.380000,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN
688,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN

In [23]:
# filterx = filtered_data1[filtered_data1['Created by'].isin(['Ayushi Lnu','Darpan Lnu', 'Kajal Garg', 'Neha Saini',
#  'Shivpreet Sandhu', 'Sweta Vanker', 'Vanshika Sachdeva','sweta.vanker','Miriam Charow','mina.navaei'])]

# start_date1 = '2025-10-13 00:00:00'
# end_date1 = '2025-10-20 23:59:59'

# filtery = filterx[(filterx['Invoice Created Date'] >= start_date1) & (filtered_data1['Invoice Created Date'] <= end_date1)]

# filtery.head(1)

In [24]:
filtered_data2.shape

(101, 65)

In [25]:
filtered_data1['Approver Name'].unique()

array(['AutoApprovalJob', nan, 'Sweta Vanker', 'Vanshika Sachdeva'],
      dtype=object)

In [26]:
distinct_values = filtered_data1['Approver Name'].dropna().unique()


value_to_exclude = 'AutoApprovalJob'
filtered_distinct = distinct_values[distinct_values != value_to_exclude]

print(filtered_distinct)

['Sweta Vanker' 'Vanshika Sachdeva']

In [27]:
filter3 = filtered_data1['Approver Name'].isin(filtered_distinct)

start_date2 = S_Date1
end_date2 = E_Date1

filter4 = (filtered_data1['Invoice Approval Date'] >= start_date1) & (filtered_data1['Invoice Approval Date'] <= end_date1)

filtered_data3 = filtered_data1[filter3 & filter4]

filtered_data3.head(2)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
660,14134,Christie Gricelda,Contractor (Affiliated Provider),238562,1635,Yes,UNITED STATES OF AMERICA,TEXAS,184039418,"SWBC Professional Employer Services V, LLC",2025-07-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184768747,185177533,2025-01-22 10:55:34.960000,Active,ST,In Person,185317101,Approved,2026-05-07,Vanshika Sachdeva,NaN,2026-05-04 09:08:44.303,14134,2026-05-08 00:30:57.903000,62,Hourly Rate,4,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,0,4,0,248,USD,0,0,248,NaN,LifeWorks-US,NaN,NaN,NaN
717,184003755,Forbes (ONSITE BLACK) Latasha,Contractor (Affiliated Provider),SUP-019604,184001797,Yes,UNITED STATES OF AMERICA,NEW YORK,184050564,Blackstone Administrative Services Partnership...,2026-01-01 00:00:00,NaN,NaN,1,Per Hour,184881968,185322433,2025-12-11 00:00:00,Active,ST,In Person,185317583,Approved,2026-05-06,Sweta Vanker,NaN,2026-05-05 13:30:49.420,184003755,NaN,0,Hourly Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN

In [28]:
filtered_data3.shape

(10, 65)

In [29]:
filter5 = filtered_data1['Approver Name'] == 'AutoApprovalJob'

start_date3 = S_Date2
end_date4 = E_Date2

filter6 = (filtered_data1['Invoice Approval Date'] >= start_date3) & (filtered_data1['Invoice Approval Date'] <= end_date4)

filtered_data4 = filtered_data1[filter5 & filter6]

filtered_data4.head(2)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
659,14134,Christie Gricelda,Contractor (Affiliated Provider),238562,1635,Yes,UNITED STATES OF AMERICA,TEXAS,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184930575,185378310,2026-04-13 06:29:39.560000,Closed,ST,In Person,185317094,Approved,2026-05-06,AutoApprovalJob,NaN,2026-05-04 08:56:53.710,14134,2026-05-06 00:30:51.473000,65,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,65,USD,0,0,65,NaN,LifeWorks-US,NaN,NaN,NaN
661,14134,Christie Gricelda,Contractor (Affiliated Provider),238562,1635,Yes,UNITED STATES OF AMERICA,TEXAS,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184927084,185375547,2026-04-08 06:25:45.747000,Active,ST,In Person,185317105,Approved,2026-05-06,AutoApprovalJob,NaN,2026-05-04 09:14:19.460,14134,2026-05-06 00:30:51.553000,65,Hourly Rate,3,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0,3,0,195,USD,0,0,195,NaN,LifeWorks-US,NaN,NaN,NaN

In [30]:
filtered_data4.shape

(123, 65)

In [31]:
combine_filtered = pd.concat([filtered_data2,filtered_data3,filtered_data4],ignore_index = True)
combine_filtered.head(2)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number
0,498335,Garnham Steven,Contractor (Affiliated Provider),419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184909998,185356976,2026-03-30 10:34:37.110000,Closed,SA,Video-Counselling,185317458,Approved,NaT,NaN,NaN,2026-05-05 03:14:10.037,Vanshika Sachdeva,2026-05-06 00:30:53.380000,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN
1,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN

In [32]:
combine_filtered.shape

(234, 65)

In [33]:
combine_filtered['concat'] = combine_filtered['Activity ID'].astype(str) + '-' + combine_filtered['Invoice ID'].astype(str)
combine_filtered.head(2)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
0,498335,Garnham Steven,Contractor (Affiliated Provider),419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184909998,185356976,2026-03-30 10:34:37.110000,Closed,SA,Video-Counselling,185317458,Approved,NaT,NaN,NaN,2026-05-05 03:14:10.037,Vanshika Sachdeva,2026-05-06 00:30:53.380000,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185356976-185317458
1,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459

In [34]:
Ap_combine_data = pd.read_excel(WD_Files_path)
Ap_combine_data.head(1)

,Batch_Number,Status,Supplier_Invoice_Number,Supplier,Company,Currency_Reference,Default_Tax_Option_Reference,Line,Invoice_Date,Invoice_Received_Date,Control_Amount_Total,Payment_Terms_Reference,Memo,Spend_Category_Reference,Tax_Applicability_Reference,Tax_Code_Reference,Extended_Amount,Project,Cost_Center,Line_of_Business,Trust,User_ID,Message
0,Symphoni_PR_Invoice_GBR_2026-05-07.xlsx|31662|...,Success,185385862-185317575,SUP-010419,CO102,USD,CALC_TAX_DUE,NaN,2026-05-05,2026-05-05,60.0,NET_15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
ap_filter = Ap_combine_data['Status'] == 'Success'

Ap_combine_success_data = Ap_combine_data[ap_filter]

Ap_combine_success_data.head(2)

,Batch_Number,Status,Supplier_Invoice_Number,Supplier,Company,Currency_Reference,Default_Tax_Option_Reference,Line,Invoice_Date,Invoice_Received_Date,Control_Amount_Total,Payment_Terms_Reference,Memo,Spend_Category_Reference,Tax_Applicability_Reference,Tax_Code_Reference,Extended_Amount,Project,Cost_Center,Line_of_Business,Trust,User_ID,Message
0,Symphoni_PR_Invoice_GBR_2026-05-07.xlsx|31662|...,Success,185385862-185317575,SUP-010419,CO102,USD,CALC_TAX_DUE,NaN,2026-05-05,2026-05-05,60.0,NET_15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Symphoni_PR_Invoice_GBR_2026-05-07.xlsx|31662|...,Success,185385735-185317970,331842,CO120,USD,CALC_TAX_DUE,NaN,2026-05-06,2026-05-06,90.0,NET_15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
unmatched_records = combine_filtered[~combine_filtered['concat'].isin(Ap_combine_success_data['Supplier_Invoice_Number'])] #remove ~ to get matched records
print(f"Unmatched records : {len(unmatched_records)}")
unmatched_records.head(2)

Unmatched records : 97

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
0,498335,Garnham Steven,Contractor (Affiliated Provider),419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184909998,185356976,2026-03-30 10:34:37.110000,Closed,SA,Video-Counselling,185317458,Approved,NaT,NaN,NaN,2026-05-05 03:14:10.037,Vanshika Sachdeva,2026-05-06 00:30:53.380000,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185356976-185317458
1,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459

In [37]:
Ap_combine_data_prev = pd.read_excel(Prev_WD_Files_path,sheet_name= 'WD')
Ap_combine_data_prev.head(2)

,Batch_Number,Status,Supplier_Invoice_Number,Supplier,Company,Currency_Reference,Default_Tax_Option_Reference,Line,Invoice_Date,Invoice_Received_Date,Control_Amount_Total,Payment_Terms_Reference
0,Symphoni_PR_Invoice_USA_2026-04-30.xlsx|31511|...,Success,185351426-185315816,129754,CO102,USD,CALC_TAX_DUE,NaN,2026-04-29,2026-04-29,200.0,NET_15
1,Symphoni_PR_Invoice_USA_2026-04-30.xlsx|31511|...,Success,185351964-185315695,SUP-015241,CO120,USD,CALC_TAX_DUE,NaN,2026-04-28,2026-04-28,80.0,NET_15

In [38]:
New_unmatched_records = unmatched_records[~unmatched_records['concat'].isin(Ap_combine_data_prev['Supplier_Invoice_Number'])] #remove ~ to get matched records
print(f"Unmatched records : {len(New_unmatched_records)}")
New_unmatched_records.head(2)

Unmatched records : 48

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
1,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461

In [39]:
print(f"Count of total payable zero is : {len(New_unmatched_records[(New_unmatched_records['Total Payable']==0) & (New_unmatched_records['Total Invoice']==0 )])}")
New_unmatched_records[(New_unmatched_records['Total Payable']==0) & (New_unmatched_records['Total Invoice']==0 )]

Count of total payable zero is : 23

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
14,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184045167,"NORTHSIDE HOSPITAL, INC. Humana id 707361",2024-07-01 00:00:00,NaN,NaN,16,Per Employee Per Month,184574517,184911097,2023-11-28 19:57:04.343000,Closed,ST,Tele-Counselling,185317467,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-05 07:26:20.787,Vanshika Sachdeva,NaN,0,Hourly Rate,0.75,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0,0.75,0,0.75,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184911097-185317467
16,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184049471,Columbia University - employees,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184520488,184834954,2023-08-21 14:18:44.210000,Closed,ST,Tele-Counselling,185317469,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-05 07:27:35.037,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184834954-185317469
17,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184045585,Humana Inc - Associate - Non-California Lives,2024-08-01 00:00:00,NaN,NaN,17,Per Employee Per Month,184803505,185222217,2025-04-18 08:46:42.280000,Active,ST,Tele-Counselling,185317470,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-05 07:32:23.197,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185222217-185317470
18,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046244,"University Health System, Inc",2024-03-01 00:00:00,NaN,NaN,16,Per Employee Per Month,184344564,184562270,2022-10-04 16:50:49.860000,Active,ST,Tele-Counselling,185317471,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-05 07:34:04.143,Vanshika Sachdeva,NaN,0,Hourly Rate,0.75,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0,0.75,0,0.75,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184562270-185317471
22,26626,Dummy Provider – Canada Cross Border,Contractor (Affiliated Provider),NaN,NaN,No,CANADA,ONTARIO,1090180,"Ross University, School of Veterinary Medicine...",2025-08-01 00:00:00,NaN,NaN,3,Flat Rate,184897798,185342220,2026-02-12 17:50:01.727000,Closed,ST2,Tele-Counselling,185317531,Approved,NaT,NaN,NaN,2026-05-05 11:15:50.160,Ayushi Lnu,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,CAD,0,0,0,Cross Border 11708575 - 9061754- AL,Symphoni,NaN,NaN,NaN,185342220-185317531
56,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046284,Olathe Public Schools USD #233,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184625324,184981967,2024-03-11 13:45:06.660000,Closed,ST,Tele-Counselling,185318222,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:04:22.307,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184981967-185318222
57,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184909729,185356655,2026-03-27 16:04:04.623000,Active,ST,Tele-Counselling,185318223,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:04:56.910,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN,185356655-185318223
58,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046246,South Broward Hospital District D/B/A Memorial...,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184835127,185262885,2025-07-18 11:32:42.983000,Active,ST,Tele-Counselling,185318224,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:05:29.887,Vanshika Sachdeva,NaN,0,Hourly Rate,0.75,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0,0.75,0,0.75,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185262885-185318224
59,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184049509,Bloomberg US,2026-01-01 00:00:00,NaN,NaN,16,Per Employee Per Month,184851404,185283887,2025-09-08 08:06:30.247000,Active,ST,Tele-Counselling,185318225,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:06:06.530,Vanshika Sachdeva,NaN,0,Hourly Rate,0.75,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0,0.75,0,0.75,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185283887-185318225
60,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046016,Mississippi State University (Employee & Staf...,2025-09-01 00:00:00,NaN,NaN,9,Per Employee Per Month,184337020,184551076,2022-09-22 13:06:14.783000,Active,ST,Tele-Counselling,185318226,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:06:43.783,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184551076-185318226
61,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184045223,ROMAN CATHOLIC BISHOP OF LOUISVILLE (Humana id...,2024-07-01 00:00:00,NaN,NaN,9,Per Employee Per Month,184347617,184566818,2022-10-10 11:44:39.343000,Active,ST,Tele-Counselling,185318227,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:07:34.803,Vanshika Sachdeva,NaN,0,Hourly Rate,1.25,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.25,0,1.25,0,1.25,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184566818-185318227
62,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184868833,185306296,2025-10-29 17:18:00.483000,Active,ST,Video-Counselling,185318228,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:08:13.707,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN,185306296-185318228
63,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184868844,185306308,2025-10-29 17:33:50.113000,Active,ST,Video-Counselling,185318229,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:08:46.940,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN,185306308-185318229
64,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184584939,184925608,2023-12-18 18:57:51.433000,Closed,ST,Tele-Counselling,185318230,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:09:29.440,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN,184925608-185318230
65,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184049471,Columbia University - employees,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184520488,184834954,2023-08-21 14:18:44.210000,Closed,ST,Tele-Counselling,185318231,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:10:07.723,Vanshika Sachdeva,NaN,0,Hourly Rate,1.25,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.25,0,1.25,0,1.25,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184834954-185318231
66,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184432607,184700422,2023-03-10 11:51:25.193000,Active,ST,Tele-Counselling,185318232,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:10:52.047,Vanshika Sachdeva,NaN,0,Hourly Rate,0.5,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0,0.5,0,0.5,0,0,USD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN,184700422-185318232
67,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184046449,"Citibank, NA - USA",2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184477041,184768877,2023-05-24 11:08:32.840000,Closed,ST,Tele-Counselling,185318233,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:11:35.333,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,LifeWorks-US,NaN,NaN,NaN,184768877-185318233
68,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184049471,Columbia University - employees,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184520488,184834954,2023-08-21 14:18:44.210000,Closed,ST,Tele-Counselling,185318234,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:12:10.087,Vanshika Sachdeva,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,184834954-185318234
69,184000902,Help Better,Contractor (Affiliated Provider),NaN,NaN,No,UNITED STATES OF AMERICA,CALIFORNIA,184045585,Humana Inc - Associate - Non-California Lives,2024-08-01 00:00:00,NaN,NaN,17,Per Employee Per Month,184794003,185209828,2025-03-24 21:07:27.493000,Active,ST,Tele-Counselling,185318235,Approved,NaT,NaN,1 April - 30 April 2026,2026-05-07 04:13:26.877,Vanshika Sachdeva,NaN,0,Hourly Rate,0.75,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,0,0.75,0,0.75,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185209828-185318235
102,184003755,Forbes (ONSITE BLACK) Latasha,Contractor (Affiliated Provider),SUP-019604,184001797,Yes,UNITED STATES OF AMERICA,NEW YORK,184050564,Blackstone Administrative Services Partnership...,2026-01-01 00:00:00,NaN,NaN,1,Per Hour,184881968,185322433,2025-12-11 00:00:00,Active,ST,In Person,185317583,Approved,2026-05-06,Sweta Vanker,NaN,2026-05-05 13:30:49.420,184003755,NaN,0,Hourly Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185322433-185317583
103,184003755,Forbes (ONSITE BLACK) Latasha,Contractor (Affiliated Provider),SUP-019604,184001797,Yes,UNITED STATES OF AMERICA,NEW YORK,184050564,Blackstone Administrative Services Partnership...,2026-01-01 00:00:00,NaN,NaN,1,Per Hour,184885580,185326995,2025-12-30 15:41:12.460000,Closed,ST,In Person,185317584,Approved,2026-05-06,Sweta Vanker,NaN,2026-05-05 13:31:07.117,184003755,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185326995-185317584
104,184003755,Forbes (ONSITE BLACK) Latasha,Contractor (Affiliated Provider),SUP-019604,184001797,Yes,UNITED STATES OF AMERICA,NEW YORK,184050564,Blackstone Administrative Services Partnership...,2026-01-01 00:00:00,NaN,NaN,1,Per Hour,184888557,185330528,2026-01-08 00:00:00,Closed,ST,In Person,185317586,Approved,2026-05-06,Sweta Vanker,NaN,2026-05-05 13:31:37.197,184003755,NaN,0,Hourly Rate,3,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,3,0,3,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185330528-185317586
109,184003755,Forbes (ONSITE BLACK) Latasha,Contractor (Affiliated Provider),SUP-019604,184001797,Yes,UNITED STATES OF AMERICA,NEW YORK,184050564,Blackstone Administrative Services Partnership...,2026-01-01 00:00:00,NaN,NaN,1,Per Hour,184871172,185309282,2025-11-06 00:00:00,Closed,ST,In Person,185318332,Approved,2026-05-08,Vanshika Sachdeva,NaN,2026-05-07 12:20:48.220,184003755,NaN,0,Hourly Rate,1,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,1,0,0,USD,0,0,0,NaN,Symphoni,NaN,NaN,NaN,185309282-185318332

In [40]:
print(f"Total records are : {len(New_unmatched_records[(New_unmatched_records['Total Payable']!=0) | (New_unmatched_records['Total Invoice']!=0 )])}")
New_unmatched_records_nonzero = New_unmatched_records[(New_unmatched_records['Total Payable']!=0) | (New_unmatched_records['Total Invoice']!=0 )]
New_unmatched_records_nonzero.head()

Total records are : 25

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
1,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,2,0,2,0,400,USD,0,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,100,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,100,USD,NaN,NaN,100,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,275,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,275,USD,NaN,NaN,275,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462

In [41]:
New_unmatched_records_nonzero.shape

(25, 66)

In [42]:
New_unmatched_records_nonzero[New_unmatched_records_nonzero.duplicated(subset=['concat'], keep=False)]
#Contrast with other keep values:

#keep='first' (default): Marks duplicates as True except for the first occurrence.
#keep='last': Marks duplicates as True except for the last occurrence.
#keep = False : It shows all occurrences of duplicates, including the first appearance.

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,100,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,100,USD,NaN,NaN,100,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,275,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,275,USD,NaN,NaN,275,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462
6,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,100,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,100,USD,NaN,NaN,100,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462
7,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,275,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,275,USD,NaN,NaN,275,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462
8,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463
9,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463
10,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464
11,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464
12,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,139.75,0,USD,0,0,139.75,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465
13,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465
20,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512
21,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512
47,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844
48,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844
49,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845
50,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845

In [43]:
#unmatched_records_nonzero = unmatched_records_nonzero.drop(7)
#unmatched_records_nonzero = unmatched_records_nonzero.drop(8)
#unmatched_records_nonzero = unmatched_records_nonzero.drop(70)
#unmatched_records_nonzero = unmatched_records_nonzero.drop(71)

In [44]:
print(len(New_unmatched_records_nonzero[New_unmatched_records_nonzero.duplicated(subset=['concat'], keep=False)]))
New_unmatched_records_nonzero[New_unmatched_records_nonzero.duplicated(subset=['concat'], keep=False)]

18

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Regular Rate Billable \nHours,Regular Rate Non-Billable \nHours,No Show \nFee,No Show \nType,No Show Billable\nHours,No Show Non-Billable\nHours,Case Management Fee,Case Management Type,Case Management Billble Hours,Case Management Non-Billble Hours,Special Rate Fee,Special Rate Type,Special Rate Billable\nHours,Special Rate Non-Billable\nHours,Other \nBillable\nHours,Other \nNon-Billable\nHours,Staff\nBillable\n Hours,Staff\nNon-Billable\n Hours,Total \nBillable\nHours,Total \nNon-Billable\nHours,Total \nPayable\nHours,Total \nNon-Payable\nHours,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Expenses non Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,100,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,100,USD,NaN,NaN,100,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,275,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,275,USD,NaN,NaN,275,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,107.25,0,USD,0,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462
6,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,100,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,100,USD,NaN,NaN,100,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462
7,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,275,Hourly Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,275,USD,NaN,NaN,275,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462
8,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463
9,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463
10,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464
11,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464
12,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,139.75,0,USD,0,0,139.75,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465
13,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465
20,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512
21,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512
47,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844
48,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844
49,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,81.25,0,USD,0,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845
50,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,225,Case Rate,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,1,NaN,225,USD,NaN,NaN,225,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845

In [45]:
New_unmatched_records_nonzero.drop_duplicates(subset=['concat'], inplace= True)

C:\Users\gaurav.trivedi\AppData\Local\Temp\ipykernel_22784\3356335658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_unmatched_records_nonzero.drop_duplicates(subset=['concat'], inplace= True)

In [46]:
#unmatched_records_nonzero.loc[29,'Total Payable'] #To check individual data

In [47]:
#unmatched_records_nonzero.loc[16,'Total Payable'] = 250

In [48]:
#unmatched_records_nonzero.loc[16,'Total Invoice'] = 250

In [49]:
#unmatched_records_nonzero = unmatched_records_nonzero.drop(17)

In [50]:
#unmatched_records_nonzero.loc[29,'Total Payable'] #Validated

In [51]:
#unmatched_records_nonzero.loc[[16]] #Validated

In [52]:
New_unmatched_records_nonzero.shape

(15, 66)

In [53]:
New_unmatched_records_nonzero[New_unmatched_records_nonzero.duplicated(subset=['Invoice ID'], keep=False)]

Empty DataFrame
Columns: [Provider ID, Provider Name, Employment Type, Supplier ID, Vendor ID, Pay Vendor Directly (Y/N)?, Provider Country, Provider  Province/State, Org ID, Org Name, Renewal Date, Max hours for contract period, Provider Email Type, Model Number, Fee Type, Case ID, Activity ID, Activity Opened Date, Activity Status, Service Code, Modality, Invoice ID, Invoice Status, Invoice Approval Date, Approver Name, Provider Invoice Number, Invoice Created Date, Created by, Export Date, Regular Rate Fee, Regular Rate Type, Regular Rate Billable
Hours, Regular Rate Non-Billable
Hours, No Show
Fee, No Show
Type, No Show Billable
Hours, No Show Non-Billable
Hours, Case Management Fee, Case Management Type, Case Management Billble Hours, Case Management Non-Billble Hours, Special Rate Fee, Special Rate Type, Special Rate Billable
Hours, Special Rate Non-Billable
Hours, Other
Billable
Hours, Other
Non-Billable
Hours, Staff
Billable
 Hours, Staff
Non-Billable
 Hours, Total
Billable
Hours, Total
Non-Billable
Hours, Total
Payable
Hours, Total
Non-Payable
Hours, Total Hours, Taxes, Total Invoice, Currency, Expenses Payable, Expenses  non Payable, Total Payable, Comment, Source, Taxes: Province/State, Tax Type, Tax Account Number, concat]
Index: []

In [54]:
New_unmatched_records_nonzero.columns

Index(['Provider ID', 'Provider Name', 'Employment Type', 'Supplier ID',
       'Vendor ID', 'Pay Vendor Directly (Y/N)?', 'Provider Country',
       'Provider  Province/State', 'Org ID', 'Org Name', 'Renewal Date',
       'Max hours for contract period', 'Provider Email Type', 'Model Number',
       'Fee Type', 'Case ID', 'Activity ID', 'Activity Opened Date',
       'Activity Status', 'Service Code', 'Modality', 'Invoice ID',
       'Invoice Status', 'Invoice Approval Date', 'Approver Name',
       'Provider Invoice Number', 'Invoice Created Date', 'Created by',
       'Export Date', 'Regular Rate Fee', 'Regular Rate Type',
       'Regular Rate Billable \nHours', 'Regular Rate Non-Billable \nHours',
       'No Show \nFee', 'No Show \nType', 'No Show Billable\nHours',
       'No Show Non-Billable\nHours', 'Case Management Fee',
       'Case Management Type', 'Case Management Billble Hours',
       'Case Management Non-Billble Hours', 'Special Rate Fee',
       'Special Rate Type', 'Special Rate Billable\nHours',
       'Special Rate Non-Billable\nHours', 'Other \nBillable\nHours',
       'Other \nNon-Billable\nHours', 'Staff\nBillable\n Hours',
       'Staff\nNon-Billable\n Hours', 'Total \nBillable\nHours',
       'Total \nNon-Billable\nHours', 'Total \nPayable\nHours',
       'Total \nNon-Payable\nHours', 'Total Hours', 'Taxes', 'Total Invoice',
       'Currency', 'Expenses Payable', 'Expenses  non Payable',
       'Total Payable', 'Comment', 'Source', 'Taxes: Province/State',
       'Tax Type', 'Tax Account Number', 'concat'],
      dtype='object', name=0)

In [55]:
New_data = New_unmatched_records_nonzero.drop(['Regular Rate Billable \nHours', 'Regular Rate Non-Billable \nHours',
       'No Show \nFee', 'No Show \nType', 'No Show Billable\nHours',
       'No Show Non-Billable\nHours', 'Case Management Fee',
       'Case Management Type', 'Case Management Billble Hours',
       'Case Management Non-Billble Hours', 'Special Rate Fee',
       'Special Rate Type', 'Special Rate Billable\nHours',
       'Special Rate Non-Billable\nHours', 'Other \nBillable\nHours',
       'Other \nNon-Billable\nHours', 'Staff\nBillable\n Hours',
       'Staff\nNon-Billable\n Hours', 'Total \nBillable\nHours',
       'Total \nNon-Billable\nHours', 'Total \nPayable\nHours',
       'Total \nNon-Payable\nHours', 'Expenses  non Payable'], axis=1)

In [56]:
New_data.shape

(15, 43)

In [57]:
## now next step is check and if

In [58]:
New_data.columns

Index(['Provider ID', 'Provider Name', 'Employment Type', 'Supplier ID',
       'Vendor ID', 'Pay Vendor Directly (Y/N)?', 'Provider Country',
       'Provider  Province/State', 'Org ID', 'Org Name', 'Renewal Date',
       'Max hours for contract period', 'Provider Email Type', 'Model Number',
       'Fee Type', 'Case ID', 'Activity ID', 'Activity Opened Date',
       'Activity Status', 'Service Code', 'Modality', 'Invoice ID',
       'Invoice Status', 'Invoice Approval Date', 'Approver Name',
       'Provider Invoice Number', 'Invoice Created Date', 'Created by',
       'Export Date', 'Regular Rate Fee', 'Regular Rate Type', 'Total Hours',
       'Taxes', 'Total Invoice', 'Currency', 'Expenses Payable',
       'Total Payable', 'Comment', 'Source', 'Taxes: Province/State',
       'Tax Type', 'Tax Account Number', 'concat'],
      dtype='object', name=0)

In [59]:
New_data.head(1)

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat
1,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,0,400,USD,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459

In [60]:

New_data['check'] = (New_data['Regular Rate Fee'] * New_data['Total Hours']) == New_data['Total Payable']

In [61]:
pd.set_option('display.max_rows',None)
New_data = New_data.reset_index(drop=True)
New_data

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat,check
0,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,0,400,USD,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459,False
1,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461,False
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462,False
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463,False
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464,False
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,0,NaN,0,139.75,0,USD,0,139.75,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465,False
6,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512,False
7,4032,Continuum R3,NaN,236307,409,Yes,UNITED STATES OF AMERICA,MICHIGAN,184041509,First Access Trauma or Dedicated counsellor,2026-01-01 00:00:00,NaN,NaN,NaN,Per Hour,184936149,185384807,2026-04-28 11:24:46.780000,Closed,DBR,Video-Counselling,185317706,Approved,NaT,NaN,835964-1,2026-05-05 17:11:56.683,Kimberly Winters,NaN,155,Hourly Rate,3,0,465,USD,25,490,KW,Symphoni,NaN,NaN,NaN,185384807-185317706,False
8,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844,False
9,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845,False
10,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184050563,Veterinary Professional Assistance Program,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184900375,185345706,2026-02-23 08:15:36.147000,Closed,SM,Webinar,185317846,Approved,NaT,NaN,185345706,2026-05-06 08:10:57.873,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345706-185317846,False
11,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028300,Enviri Corporation,2025-10-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184889829,185332131,2026-01-13 15:18:24.777000,Closed,SM,Webinar,185319107,Approved,NaT,NaN,185332131,2026-05-11 11:06:47.073,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185332131-185319107,False
12,14073,Nichols Abayomi,Contractor (Affiliated Provider),226682,NaN,No,UNITED STATES OF AMERICA,INDIANA,184000004,Internal EFAP for LifeWorks + WRP referrals,2026-05-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184933219,185381391,2026-04-20 13:03:33.837000,Active,ST,Video-Counselling,185318267,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 09:58:15.160,14073,2026-05-09 00:31:04.123000,60,Hourly Rate,1,0,60,USD,0,60,NaN,Symphoni,NaN,NaN,NaN,185381391-185318267,True
13,14073,Nichols Abayomi,Contractor (Affiliated Provider),226682,NaN,No,UNITED STATES OF AMERICA,INDIANA,184000004,Internal EFAP for LifeWorks + WRP referrals,2026-05-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184933219,185381391,2026-04-20 13:03:33.837000,Active,ST,Video-Counselling,185318319,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 11:44:04.537,14073,2026-05-09 00:31:04.420000,70,Hourly Rate,1,0,70,USD,0,70,NaN,Symphoni,NaN,NaN,NaN,185381391-185318319,True
14,16748,Tinsley Julie,Contractor (Affiliated Provider),243504,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184056739,Health First Inc - MetLife,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184903147,185350848,2026-03-12 12:24:17.260000,Active,ST,In Person,185318330,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 12:15:54.093,16748,2026-05-09 00:31:04.500000,60,Hourly Rate,4,0,240,USD,0,240,NaN,Symphoni,NaN,NaN,NaN,185350848-185318330,True

In [62]:
# New_data[New_data['check'] == False]

In [63]:
# New_data.loc[95,'Total Payable'] = 508.50 #Replacing it with correct amount
# New_data.loc[96,'Total Payable'] = 508.50 #Replacing it with correct amount
# New_data.loc[7,'Total Payable'] = 508.50 #Replacing it with correct amount
# New_data.loc[7,'Total Invoice'] = 450 #Replacing it with correct amount

In [64]:
New_data[New_data['Provider ID'] == 1542]

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat,check
1,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461,False
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462,False
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463,False
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464,False
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,0,NaN,0,139.75,0,USD,0,139.75,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465,False
6,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512,False
8,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844,False
9,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845,False
10,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184050563,Veterinary Professional Assistance Program,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184900375,185345706,2026-02-23 08:15:36.147000,Closed,SM,Webinar,185317846,Approved,NaT,NaN,185345706,2026-05-06 08:10:57.873,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345706-185317846,False
11,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028300,Enviri Corporation,2025-10-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184889829,185332131,2026-01-13 15:18:24.777000,Closed,SM,Webinar,185319107,Approved,NaT,NaN,185332131,2026-05-11 11:06:47.073,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185332131-185319107,False

In [65]:
New_data['Tax code'] = New_data.apply(
    lambda row: 'ONA' if row['Provider ID'] == 1542 else 'EXEMPT',
    axis=1
)
#.apply method is slower for large dataset

In [66]:
# New_data['tax'] = np.where(
#     New_data['Provider ID'] == 1542,
#     'ONA',
#     'EXEMPT'
# ) #This is for large dataset its faster

In [67]:
New_data.head()

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat,check,Tax code
0,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,0,400,USD,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459,False,EXEMPT
1,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461,False,ONA
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462,False,ONA
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463,False,ONA
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464,False,ONA

In [68]:
def assign_cost_centre(row):
    if row['Service Code'] == 'WRP' and row['Provider  Province/State'] == 'CALIFORNIA':
        return 'C4199'
    elif row['Service Code'] == 'SA' and row['Provider  Province/State'] == 'CALIFORNIA':
        return 'C4199'
    elif row['Service Code'] == 'ST2' and row['Provider  Province/State'] == 'CALIFORNIA':
        return 'C4199'
    elif row['Service Code'] == 'ST' and row['Provider  Province/State'] == 'CALIFORNIA':
        return 'C4199'
    elif row['Service Code'] == 'AR' and row['Provider  Province/State'] == 'CALIFORNIA':
        return 'C4199'
    elif row['Service Code'] == 'WRP':
        return 'C4103'
    elif row['Service Code'] == 'SA':
        return 'C4103'
    elif row['Service Code'] == 'ST2':
        return 'C4156'
    elif row['Service Code'] == 'ST':
        return 'C4156'
    elif row['Service Code'] == 'AR':
        return 'C4156'
    elif row['Service Code'] == 'Knox Keene':
        return 'C4199'
    elif row['Service Code'] == 'SM':
        return 'C4305'
    elif row['Service Code'] == 'WSH':
        return 'C4305'
    elif row['Service Code'] == 'HLC':
        return 'C4507'
    elif row['Service Code'] == 'SC':
        return 'C4507'
    elif row['Service Code'] == 'SL':
        return 'C4507'
    elif row['Service Code'] == 'LC':
        return 'C4507'
    elif row['Service Code'] == 'DBR':
        return 'C4120'
    else :
        return 'C4120'

New_data['Cost Centre'] = New_data.apply(assign_cost_centre,axis = 1)

In [69]:
New_data

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat,check,Tax code,Cost Centre
0,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,0,400,USD,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459,False,EXEMPT,C4103
1,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461,False,ONA,C4305
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462,False,ONA,C4305
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463,False,ONA,C4305
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464,False,ONA,C4305
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,0,NaN,0,139.75,0,USD,0,139.75,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465,False,ONA,C4305
6,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512,False,ONA,C4305
7,4032,Continuum R3,NaN,236307,409,Yes,UNITED STATES OF AMERICA,MICHIGAN,184041509,First Access Trauma or Dedicated counsellor,2026-01-01 00:00:00,NaN,NaN,NaN,Per Hour,184936149,185384807,2026-04-28 11:24:46.780000,Closed,DBR,Video-Counselling,185317706,Approved,NaT,NaN,835964-1,2026-05-05 17:11:56.683,Kimberly Winters,NaN,155,Hourly Rate,3,0,465,USD,25,490,KW,Symphoni,NaN,NaN,NaN,185384807-185317706,False,EXEMPT,C4120
8,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844,False,ONA,C4305
9,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845,False,ONA,C4305
10,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184050563,Veterinary Professional Assistance Program,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184900375,185345706,2026-02-23 08:15:36.147000,Closed,SM,Webinar,185317846,Approved,NaT,NaN,185345706,2026-05-06 08:10:57.873,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345706-185317846,False,ONA,C4305
11,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028300,Enviri Corporation,2025-10-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184889829,185332131,2026-01-13 15:18:24.777000,Closed,SM,Webinar,185319107,Approved,NaT,NaN,185332131,2026-05-11 11:06:47.073,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185332131-185319107,False,ONA,C4305
12,14073,Nichols Abayomi,Contractor (Affiliated Provider),226682,NaN,No,UNITED STATES OF AMERICA,INDIANA,184000004,Internal EFAP for LifeWorks + WRP referrals,2026-05-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184933219,185381391,2026-04-20 13:03:33.837000,Active,ST,Video-Counselling,185318267,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 09:58:15.160,14073,2026-05-09 00:31:04.123000,60,Hourly Rate,1,0,60,USD,0,60,NaN,Symphoni,NaN,NaN,NaN,185381391-185318267,True,EXEMPT,C4156
13,14073,Nichols Abayomi,Contractor (Affiliated Provider),226682,NaN,No,UNITED STATES OF AMERICA,INDIANA,184000004,Internal EFAP for LifeWorks + WRP referrals,2026-05-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184933219,185381391,2026-04-20 13:03:33.837000,Active,ST,Video-Counselling,185318319,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 11:44:04.537,14073,2026-05-09 00:31:04.420000,70,Hourly Rate,1,0,70,USD,0,70,NaN,Symphoni,NaN,NaN,NaN,185381391-185318319,True,EXEMPT,C4156
14,16748,Tinsley Julie,Contractor (Affiliated Provider),243504,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184056739,Health First Inc - MetLife,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184903147,185350848,2026-03-12 12:24:17.260000,Active,ST,In Person,185318330,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 12:15:54.093,16748,2026-05-09 00:31:04.500000,60,Hourly Rate,4,0,240,USD,0,240,NaN,Symphoni,NaN,NaN,NaN,185350848-185318330,True,EXEMPT,C4156

In [70]:
# New_data.loc[[9]]

In [71]:
#Add final columns

In [72]:
New_data = New_data.reset_index(drop=True)
New_data

,Provider ID,Provider Name,Employment Type,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Country,Provider Province/State,Org ID,Org Name,Renewal Date,Max hours for contract period,Provider Email Type,Model Number,Fee Type,Case ID,Activity ID,Activity Opened Date,Activity Status,Service Code,Modality,Invoice ID,Invoice Status,Invoice Approval Date,Approver Name,Provider Invoice Number,Invoice Created Date,Created by,Export Date,Regular Rate Fee,Regular Rate Type,Total Hours,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Source,Taxes: Province/State,Tax Type,Tax Account Number,concat,check,Tax code,Cost Centre
0,498335,Garnham Steven,NaN,419386,NaN,No,UNITED STATES OF AMERICA,PENNSYLVANIA,184053652,Canadian Pacific Kansas City - US,2025-10-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184910423,185357531,2026-03-31 16:34:09.007000,Closed,SA,Tele-Counselling,185317459,Approved,NaT,NaN,NaN,2026-05-05 03:17:19.727,Vanshika Sachdeva,NaN,400,Case Rate,2,0,400,USD,0,400,NaN,LifeWorks-US,NaN,NaN,NaN,185357531-185317459,False,EXEMPT,C4103
1,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335302,2026-01-22 11:14:18.160000,Closed,SM,Webinar,185317461,Approved,NaT,NaN,185335302,2026-05-05 04:19:56.320,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335302-185317461,False,ONA,C4305
2,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039965,MEDIATEK USA INC.,2026-01-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184891890,185335303,2026-01-22 11:14:46.720000,Closed,SM,Webinar,185317462,Approved,NaT,NaN,185335303,2026-05-05 04:23:11.847,Kajal Garg,NaN,0,NaN,0,107.25,0,USD,0,107.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185335303-185317462,False,ONA,C4305
3,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936982,185385796,2026-04-30 11:10:26.127000,Closed,SM,Webinar,185317463,Approved,NaT,NaN,185385796,2026-05-05 04:41:31.437,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385796-185317463,False,ONA,C4305
4,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184936993,185385808,2026-04-30 11:30:22.227000,Closed,SM,Webinar,185317464,Approved,NaT,NaN,185385808,2026-05-05 04:47:11.690,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185385808-185317464,False,ONA,C4305
5,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184900345,185345169,2026-02-19 20:54:18.183000,Closed,SM,Webinar,185317465,Approved,NaT,NaN,185345169,2026-05-05 05:32:18.100,Kajal Garg,NaN,0,NaN,0,139.75,0,USD,0,139.75,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345169-185317465,False,ONA,C4305
6,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,1120308,Cross Border Bookings – Canada,2026-03-01 00:00:00,NaN,NaN,18,Flat Rate,184935818,185384438,2026-04-27 17:21:29.890000,Closed,SM,Webinar,185317512,Approved,NaT,NaN,185384438,2026-05-05 10:39:51.150,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185384438-185317512,False,ONA,C4305
7,4032,Continuum R3,NaN,236307,409,Yes,UNITED STATES OF AMERICA,MICHIGAN,184041509,First Access Trauma or Dedicated counsellor,2026-01-01 00:00:00,NaN,NaN,NaN,Per Hour,184936149,185384807,2026-04-28 11:24:46.780000,Closed,DBR,Video-Counselling,185317706,Approved,NaT,NaN,835964-1,2026-05-05 17:11:56.683,Kimberly Winters,NaN,155,Hourly Rate,3,0,465,USD,25,490,KW,Symphoni,NaN,NaN,NaN,185384807-185317706,False,EXEMPT,C4120
8,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028687,Littelfuse Inc - United States EAP,2026-01-01 00:00:00,NaN,NaN,1,Per Employee Per Month,184903673,185352601,2026-03-18 13:35:24.480000,Closed,SM,Webinar,185317844,Approved,NaT,NaN,185352601,2026-05-06 08:02:32.717,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185352601-185317844,False,ONA,C4305
9,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184039076,Cross Border Bookings – UK,2026-03-01 00:00:00,NaN,NaN,18,NaN,184896597,185341699,2026-02-11 14:03:34.320000,Closed,SM,Webinar,185317845,Approved,NaT,NaN,185341699,2026-05-06 08:05:54.893,Kajal Garg,NaN,0,NaN,0,81.25,0,USD,0,81.25,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185341699-185317845,False,ONA,C4305
10,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184050563,Veterinary Professional Assistance Program,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184900375,185345706,2026-02-23 08:15:36.147000,Closed,SM,Webinar,185317846,Approved,NaT,NaN,185345706,2026-05-06 08:10:57.873,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,Symphoni,ONTARIO,Harmonized Sales Tax,736573155RT0001,185345706-185317846,False,ONA,C4305
11,1542,Nutrition at Work NDC,Contractor (Affiliated Provider),341143,184000746,Yes,CANADA,QUEBEC,184028300,Enviri Corporation,2025-10-01 00:00:00,NaN,NaN,13,Per Employee Per Month,184889829,185332131,2026-01-13 15:18:24.777000,Closed,SM,Webinar,185319107,Approved,NaT,NaN,185332131,2026-05-11 11:06:47.073,Kajal Garg,NaN,0,NaN,0,58.5,0,USD,0,58.5,KG,LifeWorks-US,ONTARIO,Harmonized Sales Tax,736573155RT0001,185332131-185319107,False,ONA,C4305
12,14073,Nichols Abayomi,Contractor (Affiliated Provider),226682,NaN,No,UNITED STATES OF AMERICA,INDIANA,184000004,Internal EFAP for LifeWorks + WRP referrals,2026-05-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184933219,185381391,2026-04-20 13:03:33.837000,Active,ST,Video-Counselling,185318267,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 09:58:15.160,14073,2026-05-09 00:31:04.123000,60,Hourly Rate,1,0,60,USD,0,60,NaN,Symphoni,NaN,NaN,NaN,185381391-185318267,True,EXEMPT,C4156
13,14073,Nichols Abayomi,Contractor (Affiliated Provider),226682,NaN,No,UNITED STATES OF AMERICA,INDIANA,184000004,Internal EFAP for LifeWorks + WRP referrals,2026-05-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184933219,185381391,2026-04-20 13:03:33.837000,Active,ST,Video-Counselling,185318319,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 11:44:04.537,14073,2026-05-09 00:31:04.420000,70,Hourly Rate,1,0,70,USD,0,70,NaN,Symphoni,NaN,NaN,NaN,185381391-185318319,True,EXEMPT,C4156
14,16748,Tinsley Julie,Contractor (Affiliated Provider),243504,NaN,No,UNITED STATES OF AMERICA,FLORIDA,184056739,Health First Inc - MetLife,2026-01-01 00:00:00,NaN,NaN,14,Per Employee Per Month,184903147,185350848,2026-03-12 12:24:17.260000,Active,ST,In Person,185318330,Approved,2026-05-09,AutoApprovalJob,NaN,2026-05-07 12:15:54.093,16748,2026-05-09 00:31:04.500000,60,Hourly Rate,4,0,240,USD,0,240,NaN,Symphoni,NaN,NaN,NaN,185350848-185318330,True,EXEMPT,C4156

In [73]:
New_data['Total Payable'].sum()

2137.5

In [74]:
New_data.columns

Index(['Provider ID', 'Provider Name', 'Employment Type', 'Supplier ID',
       'Vendor ID', 'Pay Vendor Directly (Y/N)?', 'Provider Country',
       'Provider  Province/State', 'Org ID', 'Org Name', 'Renewal Date',
       'Max hours for contract period', 'Provider Email Type', 'Model Number',
       'Fee Type', 'Case ID', 'Activity ID', 'Activity Opened Date',
       'Activity Status', 'Service Code', 'Modality', 'Invoice ID',
       'Invoice Status', 'Invoice Approval Date', 'Approver Name',
       'Provider Invoice Number', 'Invoice Created Date', 'Created by',
       'Export Date', 'Regular Rate Fee', 'Regular Rate Type', 'Total Hours',
       'Taxes', 'Total Invoice', 'Currency', 'Expenses Payable',
       'Total Payable', 'Comment', 'Source', 'Taxes: Province/State',
       'Tax Type', 'Tax Account Number', 'concat', 'check', 'Tax code',
       'Cost Centre'],
      dtype='object', name=0)

In [75]:
New_data[['Provider ID', 'Provider Name','Supplier ID','Vendor ID', 'Pay Vendor Directly (Y/N)?','Provider  Province/State',
          'Activity ID','Service Code','Cost Centre','Invoice ID','Provider Invoice Number','Invoice Created Date','Taxes','Total Invoice',
         'Currency','Expenses Payable','Total Payable','Comment','Tax code']]

,Provider ID,Provider Name,Supplier ID,Vendor ID,Pay Vendor Directly (Y/N)?,Provider Province/State,Activity ID,Service Code,Cost Centre,Invoice ID,Provider Invoice Number,Invoice Created Date,Taxes,Total Invoice,Currency,Expenses Payable,Total Payable,Comment,Tax code
0,498335,Garnham Steven,419386,NaN,No,PENNSYLVANIA,185357531,SA,C4103,185317459,NaN,2026-05-05 03:17:19.727,0,400,USD,0,400,NaN,EXEMPT
1,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185335302,SM,C4305,185317461,185335302,2026-05-05 04:19:56.320,107.25,0,USD,0,107.25,KG,ONA
2,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185335303,SM,C4305,185317462,185335303,2026-05-05 04:23:11.847,107.25,0,USD,0,107.25,KG,ONA
3,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185385796,SM,C4305,185317463,185385796,2026-05-05 04:41:31.437,81.25,0,USD,0,81.25,KG,ONA
4,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185385808,SM,C4305,185317464,185385808,2026-05-05 04:47:11.690,81.25,0,USD,0,81.25,KG,ONA
5,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185345169,SM,C4305,185317465,185345169,2026-05-05 05:32:18.100,139.75,0,USD,0,139.75,KG,ONA
6,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185384438,SM,C4305,185317512,185384438,2026-05-05 10:39:51.150,81.25,0,USD,0,81.25,KG,ONA
7,4032,Continuum R3,236307,409,Yes,MICHIGAN,185384807,DBR,C4120,185317706,835964-1,2026-05-05 17:11:56.683,0,465,USD,25,490,KW,EXEMPT
8,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185352601,SM,C4305,185317844,185352601,2026-05-06 08:02:32.717,81.25,0,USD,0,81.25,KG,ONA
9,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185341699,SM,C4305,185317845,185341699,2026-05-06 08:05:54.893,81.25,0,USD,0,81.25,KG,ONA
10,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185345706,SM,C4305,185317846,185345706,2026-05-06 08:10:57.873,58.5,0,USD,0,58.5,KG,ONA
11,1542,Nutrition at Work NDC,341143,184000746,Yes,QUEBEC,185332131,SM,C4305,185319107,185332131,2026-05-11 11:06:47.073,58.5,0,USD,0,58.5,KG,ONA
12,14073,Nichols Abayomi,226682,NaN,No,INDIANA,185381391,ST,C4156,185318267,NaN,2026-05-07 09:58:15.160,0,60,USD,0,60,NaN,EXEMPT
13,14073,Nichols Abayomi,226682,NaN,No,INDIANA,185381391,ST,C4156,185318319,NaN,2026-05-07 11:44:04.537,0,70,USD,0,70,NaN,EXEMPT
14,16748,Tinsley Julie,243504,NaN,No,FLORIDA,185350848,ST,C4156,185318330,NaN,2026-05-07 12:15:54.093,0,240,USD,0,240,NaN,EXEMPT

In [76]:
Final_output = New_data[['Provider ID', 'Provider Name','Supplier ID','Vendor ID', 'Pay Vendor Directly (Y/N)?','Provider  Province/State',
          'Activity ID','Service Code','Cost Centre','Invoice ID','Provider Invoice Number','Invoice Created Date','Taxes','Total Invoice',
         'Currency','Expenses Payable','Total Payable','Comment','Tax code','check']]
Final_output.shape

(15, 20)

In [77]:
Final_output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Provider ID                 15 non-null     object
 1   Provider Name               15 non-null     object
 2   Supplier ID                 15 non-null     object
 3   Vendor ID                   11 non-null     object
 4   Pay Vendor Directly (Y/N)?  15 non-null     object
 5   Provider  Province/State    15 non-null     object
 6   Activity ID                 15 non-null     object
 7   Service Code                15 non-null     object
 8   Cost Centre                 15 non-null     object
 9   Invoice ID                  15 non-null     object
 10  Provider Invoice Number     11 non-null     object
 11  Invoice Created Date        15 non-null     datetime64[ns]
 12  Taxes                       15 non-null     object
 13  Total Invoice               15 non-null     object
 14  Currency                    15 non-null     object
 15  Expenses Payable            15 non-null     object
 16  Total Payable               15 non-null     object
 17  Comment                     11 non-null     object
 18  Tax code                    15 non-null     object
 19  check                       15 non-null     bool
dtypes: bool(1), datetime64[ns](1), object(18)
memory usage: 2.4+ KB

In [78]:
#Final_output['Invoice Created Date'] = pd.to_datetime(Final_output['Invoice Created Date'], errors='coerce')
Final_output['Invoice Created Date'] = Final_output['Invoice Created Date'].dt.date

C:\Users\gaurav.trivedi\AppData\Local\Temp\ipykernel_22784\3399996020.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final_output['Invoice Created Date'] = Final_output['Invoice Created Date'].dt.date

In [79]:
print(Final_output.dtypes)

0
Provider ID                   object
Provider Name                 object
Supplier ID                   object
Vendor ID                     object
Pay Vendor Directly (Y/N)?    object
Provider  Province/State      object
Activity ID                   object
Service Code                  object
Cost Centre                   object
Invoice ID                    object
Provider Invoice Number       object
Invoice Created Date          object
Taxes                         object
Total Invoice                 object
Currency                      object
Expenses Payable              object
Total Payable                 object
Comment                       object
Tax code                      object
check                           bool
dtype: object

In [80]:
# Output_path = 'C:\\Gaurav\\Practice\\New folder\\Output\\Final.xlsx'
# Final_output.to_excel(Output_path,sheet_name='Not in WD-FNL',index = False)

In [81]:
df1 = filtered_data1
df2 = combine_filtered  
df3 = Ap_combine_success_data
df4 = Ap_combine_data_prev
df5 = unmatched_records
df6 = New_unmatched_records
df7 = New_unmatched_records_nonzero
df8 = New_data
df9 = Final_output

# Create Excel writer object
with pd.ExcelWriter(Output_path, engine='openpyxl') as writer:
    df1.to_excel(writer, sheet_name='Filtered', index=False)
    df2.to_excel(writer, sheet_name='Combine_filtered', index=False)
    df3.to_excel(writer, sheet_name='WD', index=False)
    df4.to_excel(writer, sheet_name='WD-prev', index=False)
    df5.to_excel(writer, sheet_name='Not in WD', index=False)
    df6.to_excel(writer, sheet_name='Not in WD Final', index=False)
    df7.to_excel(writer, sheet_name='Not in WD Final working', index=False)
    df8.to_excel(writer, sheet_name='Final', index=False)
    df9.to_excel(writer, sheet_name='Final Sorted', index=False)