In [1]:
pip install requests

Requirement already satisfied: requests in c:\users\91968\anaconda3\lib\site-packages (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\91968\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\91968\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91968\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91968\anaconda3\lib\site-packages (from requests) (3.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\91968\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\91968\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

In [31]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup

In [32]:
url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

r = requests.get(url)

print(r)

soup = BeautifulSoup(r.text,"lxml")

print(soup)

<Response [200]>
<!DOCTYPE html>
<html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.905c37.css" rel="stylesheet"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.914d0a.css" rel="stylesheet"/><meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="102988293558" property="fb:page_id"/><meta content="658873552,624500995,100000233612389" property="fb:admins"/><meta content="noodp" name="robots"/><link href="https:///www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/><link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/><meta content="website" property="og:type"/><meta content="Flipkart.com" name="og_site_name" property="og:site_name"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/><meta content="app" name="twitter:card"/><meta content="@flipkart" name="twitter:site"/><meta content="@flipkart" name="twitter:creator"/><meta content="Mobiles Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/><meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/><meta content="in" name="twitter:app:country"/><meta content="Flipkart" name="al:ios:app_name"/><meta content="742044692" name="al:ios:app_store_id"/><meta content="Flipkart" name="twitter:app:name:iphone"/><meta content="742044692" name="twitter:app:id:iphone"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/><meta content="Flipkart" name="twitter:app:name:ipad"/><meta content="742044692" name="twitter:app:id:ipad"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/><meta content="Flipkart" name="twitter:app:name:googleplay"/><meta content="com.flipkart.android" name="twitter:app:id:googleplay"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/><style>#container {
			height: 100%;
		}</style> <link href="///fk-cp-zion/css/Browse.chunk.84557f.css" rel="stylesheet"/><title>Mobiles Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta content="Mobiles Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"/><meta content="Mobiles Under 50000" name="Keywords"/> <meta content="Mobiles Under 50000- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"/><meta content="Mobiles Under 50000- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"/> <meta content="noindex" name="robots"/> <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"/> <!--[if IE 9 ]>
	<script nonce="7981130092762481229">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]--><!--[if !IE]><!--><script nonce="7981130092762481229">if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}</script><!--<![endif]--> <link href="https://www.flipkart.com/search?q=mobiles+under+50000&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=2" id="next-page-link-tag" rel="next"/><script nonce="7981130092762481229">!function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();

		if (requestAnimationFrame && performance && performance.mark) {
			requestAnimationFrame(function () {
				window.first_paint = performance.now();
				performance.mark("first_paint");
			});
		}

        // web-vitals polyfill for FID
        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-594691041"></script><script nonce="7981130092762481229">window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments)};

In [33]:
url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

r = requests.get(url)

#print(r)

soup = BeautifulSoup(r.text,"lxml")

#print(soup)

np = soup.find("a", class_ = "_1LKTO3").get("href")

print(np)

/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2

In [34]:
url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

r = requests.get(url)

#print(r)

soup = BeautifulSoup(r.text,"lxml")

#print(soup)

np = soup.find("a", class_ = "_1LKTO3").get("href")

cnp = "https://www.flipkart.com" + np

print(cnp)

https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2

In [7]:
url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

r = requests.get(url)

#print(r)

soup = BeautifulSoup(r.text,"lxml")

#print(soup)

while True : 
    
    np = soup.find("a", class_ = "_1LKTO3").get("href")

    cnp = "https://www.flipkart.com" + np

    print(cnp)

    url = cnp

    r=requests.get(url)
    soup = BeautifulSoup(r.text,"lxml")

https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1

KeyboardInterrupt:

In [35]:
for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

    url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(i)

    r = requests.get(url)

    #print(r)

    soup = BeautifulSoup(r.text,"lxml")

    #print(soup)

    #while True : 

    np = soup.find("a", class_ = "_1LKTO3").get("href")

    cnp = "https://www.flipkart.com" + np

    print(cnp)

    #url = cnp

    #r=requests.get(url)
    #soup = BeautifulSoup(r.text,"lxml")

https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=1
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=2
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=3
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=4
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=5
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=6
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=7
https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=8

In [ ]:
#checking for one page first

In [36]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
names =  soup.find_all("div",class_ = "_4rR01T")
print(names)

[<div class="_4rR01T">SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)</div>, <div class="_4rR01T">MOTOROLA Edge 30 Ultra (Interstellar Black, 256 GB)</div>, <div class="_4rR01T">Google Pixel 7 (Snow, 128 GB)</div>, <div class="_4rR01T">MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)</div>, <div class="_4rR01T">Google Pixel 7 (Obsidian, 128 GB)</div>, <div class="_4rR01T">Google Pixel 7 (Lemongrass, 128 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy A54 5G (Awesome Graphite, 256 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy S20 FE 5G (Cloud Mint, 128 GB)</div>, <div class="_4rR01T">Nothing Phone (2) (Dark Grey, 256 GB)</div>, <div class="_4rR01T">Nothing Phone (2) (White, 256 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy A54 5G (Awesome Lime, 256 GB)</div>, <div class="_4rR01T">Tecno Phantom X2 Pro (Mars Orange, 256 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy A73 5G (Awesome Gray, 256 GB)</div>, <div class="_4rR01T">SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)</div>, <div class="_4rR01T">vivo X70 Pro (Aurora Dawn, 256 GB)</div>, <div class="_4rR01T">vivo X70 Pro (Cosmic Black, 256 GB)</div>, <div class="_4rR01T">OnePlus 10T 5G (Moonstone Black, 128 GB)</div>, <div class="_4rR01T">Mi 10T Pro (Cosmic Black, 128 GB)</div>, <div class="_4rR01T">vivo V23 Pro 5G (Stardust Black, 256 GB)</div>, <div class="_4rR01T">APPLE iPhone 11 (Red, 128 GB)</div>]

In [37]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
names =  soup.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(product_name)

['SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)', 'MOTOROLA Edge 30 Ultra (Interstellar Black, 256 GB)', 'Google Pixel 7 (Snow, 128 GB)', 'MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)', 'Google Pixel 7 (Obsidian, 128 GB)', 'Google Pixel 7 (Lemongrass, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Graphite, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)', 'SAMSUNG Galaxy S20 FE 5G (Cloud Mint, 128 GB)', 'Nothing Phone (2) (Dark Grey, 256 GB)', 'Nothing Phone (2) (White, 256 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Lime, 256 GB)', 'Tecno Phantom X2 Pro (Mars Orange, 256 GB)', 'SAMSUNG Galaxy A73 5G (Awesome Gray, 256 GB)', 'SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)', 'vivo X70 Pro (Aurora Dawn, 256 GB)', 'vivo X70 Pro (Cosmic Black, 256 GB)', 'OnePlus 10T 5G (Moonstone Black, 128 GB)', 'Mi 10T Pro (Cosmic Black, 128 GB)', 'vivo V23 Pro 5G (Stardust Black, 256 GB)', 'APPLE iPhone 11 (Red, 128 GB)']

In [38]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
names =  soup.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(len(product_name))

24

In [39]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
names =  soup.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(product_name)

['SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)', 'MOTOROLA Edge 30 Ultra (Interstellar Black, 256 GB)', 'Google Pixel 7 (Snow, 128 GB)', 'MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)', 'Google Pixel 7 (Obsidian, 128 GB)', 'Google Pixel 7 (Lemongrass, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Graphite, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)', 'SAMSUNG Galaxy S20 FE 5G (Cloud Mint, 128 GB)', 'Nothing Phone (2) (Dark Grey, 256 GB)', 'Nothing Phone (2) (White, 256 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Lime, 256 GB)', 'Tecno Phantom X2 Pro (Mars Orange, 256 GB)', 'SAMSUNG Galaxy A73 5G (Awesome Gray, 256 GB)', 'SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)', 'vivo X70 Pro (Aurora Dawn, 256 GB)', 'vivo X70 Pro (Cosmic Black, 256 GB)', 'OnePlus 10T 5G (Moonstone Black, 128 GB)', 'Mi 10T Pro (Cosmic Black, 128 GB)', 'vivo V23 Pro 5G (Stardust Black, 256 GB)', 'APPLE iPhone 11 (Red, 128 GB)']

In [40]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
names =  soup.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(product_name)

price = soup.find_all("div",class_ = "_30jeq3 _1_WHN1")

for i in price :
    price = i.text
    prices.append(price)
print(prices)

['SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)', 'MOTOROLA Edge 30 Ultra (Interstellar Black, 256 GB)', 'Google Pixel 7 (Snow, 128 GB)', 'MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)', 'Google Pixel 7 (Obsidian, 128 GB)', 'Google Pixel 7 (Lemongrass, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Graphite, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)', 'SAMSUNG Galaxy S20 FE 5G (Cloud Mint, 128 GB)', 'Nothing Phone (2) (Dark Grey, 256 GB)', 'Nothing Phone (2) (White, 256 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Lime, 256 GB)', 'Tecno Phantom X2 Pro (Mars Orange, 256 GB)', 'SAMSUNG Galaxy A73 5G (Awesome Gray, 256 GB)', 'SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)', 'vivo X70 Pro (Aurora Dawn, 256 GB)', 'vivo X70 Pro (Cosmic Black, 256 GB)', 'OnePlus 10T 5G (Moonstone Black, 128 GB)', 'Mi 10T Pro (Cosmic Black, 128 GB)', 'vivo V23 Pro 5G (Stardust Black, 256 GB)', 'APPLE iPhone 11 (Red, 128 GB)']
['₹49,999', '₹44,999', '₹49,999', '₹47,999', '₹49,999', '₹47,999', '₹47,999', '₹40,999', '₹38,999', '₹27,499', '₹49,999', '₹49,999', '₹44,999', '₹40,999', '₹40,999', '₹44,999', '₹43,490', '₹49,999', '₹46,999', '₹45,999', '₹45,990', '₹47,999', '₹43,990', '₹46,999']

In [41]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
names =  soup.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(len(product_name))

price = soup.find_all("div",class_ = "_30jeq3 _1_WHN1")

for i in price :
    price = i.text
    prices.append(price)
print(len(prices))
    
desc = soup.find_all("div",class_ = "fMghEO")

for i in desc :
    desc = i.text
    description.append(desc)
print(len(description))

review = soup.find_all("div",class_ = "_3LWZlK")

for i in review :
    review = i.text
    reviews.append(review)
print(len(reviews))

24
24
24
33

In [ ]:
# since review in getting more than 24 values coz of addition reviews at the end of page , so we have select particular area of page only.

In [42]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
box = soup.find("div",class_ = "_1YokD2")

names =  box.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(len(product_name))

price = box.find_all("div",class_ = "_30jeq3 _1_WHN1")

for i in price :
    price = i.text
    prices.append(price)
print(len(prices))
    
desc = box.find_all("div",class_ = "fMghEO")

for i in desc :
    desc = i.text
    description.append(desc)
print(len(description))

review = box.find_all("div",class_ = "_3LWZlK")

for i in review :
    review = i.text
    reviews.append(review)
print(len(reviews))

24
24
24
18

In [16]:
# now its correct

In [43]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
box = soup.find("div",class_ = "_1YokD2")

names =  box.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
print(product_name)

price = box.find_all("div",class_ = "_30jeq3 _1_WHN1")

for i in price :
    price = i.text
    prices.append(price)
print(prices)
    
desc = box.find_all("div",class_ = "fMghEO")

for i in desc :
    desc = i.text
    description.append(desc)
print(description)

review = box.find_all("div",class_ = "_3LWZlK")

for i in review :
    review = i.text
    reviews.append(review)
print(reviews)

['SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)', 'MOTOROLA Edge 30 Ultra (Interstellar Black, 256 GB)', 'Google Pixel 7 (Snow, 128 GB)', 'MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)', 'Google Pixel 7 (Obsidian, 128 GB)', 'Google Pixel 7 (Lemongrass, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Graphite, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)', 'SAMSUNG Galaxy S20 FE 5G (Cloud Mint, 128 GB)', 'Nothing Phone (2) (Dark Grey, 256 GB)', 'Nothing Phone (2) (White, 256 GB)', 'SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)', 'SAMSUNG Galaxy A54 5G (Awesome Lime, 256 GB)', 'Tecno Phantom X2 Pro (Mars Orange, 256 GB)', 'SAMSUNG Galaxy A73 5G (Awesome Gray, 256 GB)', 'SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)', 'vivo X70 Pro (Aurora Dawn, 256 GB)', 'vivo X70 Pro (Cosmic Black, 256 GB)', 'OnePlus 10T 5G (Moonstone Black, 128 GB)', 'Mi 10T Pro (Cosmic Black, 128 GB)', 'vivo V23 Pro 5G (Stardust Black, 256 GB)', 'APPLE iPhone 11 (Red, 128 GB)']
['₹49,999', '₹44,999', '₹49,999', '₹47,999', '₹49,999', '₹47,999', '₹47,999', '₹40,999', '₹38,999', '₹27,499', '₹49,999', '₹49,999', '₹44,999', '₹40,999', '₹40,999', '₹44,999', '₹43,490', '₹49,999', '₹46,999', '₹45,999', '₹45,990', '₹47,999', '₹43,990', '₹46,999']
['8 GB RAM | 128 GB ROM16.76 cm (6.6 inch) Full HD+ Display50MP + 12MP + 10MP | 10MP Front Camera4500 mAh Lithium-ion BatteryQualcomm Snapdragon 8 Gen 1 Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories', '8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Full HD+ Display12MP + 12MP | 10MP Front Camera3300 mAh Lithium-ion BatteryQualcomm Snapdragon 888 Octa-Core Processor1 Year Manufacturer Warranty for Device and 6 months Manufacturer Warranty for In-Box Accessories', '12 GB RAM | 256 GB ROM16.94 cm (6.67 inch) Full HD+ Display200MP + 50MP + 12MP | 60MP Front Camera4610 mAh Lithium BatteryQualcomm Snapdragon 8+ Gen 1 Processor1 Year on Handset and 6 Months on Accessories', '8 GB RAM | 128 GB ROM16.0 cm (6.3 inch) Full HD+ Display50MP + 12MP | 10.8MP Front Camera4270 mAh BatteryGoogle Tensor G2 ProcessorNA', '12 GB RAM | 256 GB ROM16.94 cm (6.67 inch) Full HD+ Display200MP + 50MP + 12MP | 60MP Front Camera4610 mAh Lithium BatteryQualcomm Snapdragon 8+ Gen 1 Processor1 Year on Handset and 6 Months on Accessories', '8 GB RAM | 128 GB ROM16.0 cm (6.3 inch) Full HD+ Display50MP + 12MP | 10.8MP Front Camera4270 mAh BatteryGoogle Tensor G2 Processor1 Year Domestic Warranty', '8 GB RAM | 128 GB ROM16.0 cm (6.3 inch) Full HD+ Display50MP + 12MP | 10.8MP Front Camera4270 mAh BatteryGoogle Tensor G2 Processor1 Year Domestic Warranty', '8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16.26 cm (6.4 inch) Full HD+ Display50MP + 12MP + 5MP | 32MP Front Camera5000 mAh BatteryExynos 1380, Octa Core Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories', '8 GB RAM | 128 GB ROM | Expandable Upto 1 TB16.26 cm (6.4 inch) Full HD+ Display50MP + 12MP + 5MP | 32MP Front Camera5000 mAh BatteryExynos 1380, Octa Core Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories', '8 GB RAM | 128 GB ROM16.51 cm (6.5 inch) Display12MP Rear Camera4500 mAh Battery1 Year Warranty', '12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full HD+ Display50MP + 50MP | 32MP Front Camera4700 mAh Lithium ion BatteryQualcomm Snapdragon 8+ Gen 1 Processor1 Year Manufacturing Warranty', '12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full HD+ Display50MP + 50MP | 32MP Front Camera4700 mAh Lithium ion BatteryQualcomm Snapdragon 8+ Gen 1 Processor1 Year Manufacturing Warranty', '8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Full HD+ Display12MP + 12MP | 10MP Front Camera3300 mAh Lithium-ion BatteryQualcomm Snapdragon 888 Octa-Core Processor1 Year Manufacturer Warranty for Device and 6 months Manufacturer Warranty for In-Box Accessories', '8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16.26 cm (6.4 inch) Full HD+ Display50MP + 12MP + 5MP | 32MP Front Camera5000 mAh BatteryExynos 1380, Octa Core Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories', '8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16.26 cm (6.4 inch) Full HD+ Display50MP + 12MP + 5MP | 32MP Front Camera5000 mAh BatteryExynos 1380, Octa Core Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories', '12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full HD+ Display50MP + 50MP + 13MP | 32MP Front Camera5160 mAh BatteryMediaTek Dimensity 9000 MT6983 ProcessorDomestic Warranty of 12 Months on Phone & 6 Months on Accessories', '8 GB RAM | 256 GB ROM | Expandable Upto 1 TB17.02 cm (6.7 inch) Full HD+ Display108MP + 12MP + 5MP + 5MP | 32MP Front Camera5000 mAh Li-ion BatteryQualcomm Snapdragon 778G Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box', '8 GB RAM | 128 GB ROM16.76 cm (6.6 inch) Full HD+ Display50MP + 12MP + 10MP | 10MP Front Camera4500 mAh Lithium-ion BatteryQualcomm Snapdragon 8 Gen 1 Processor1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories', '12 GB RAM | 256 GB ROM16.66 cm (6.56 inch) Full HD+ Display50MP + 12MP + 12MP + 8MP | 32MP Front Camera4450 mAh BatteryMediaTek Dimensity 1200 Processor1 Year for Handset and 6 Months for In-box Accessories', '12 GB RAM | 256 GB ROM16.66 cm (6.56 inch) Full HD+ Display50MP + 12MP + 12MP + 8MP | 32MP Front Camera4450 mAh BatteryMediaTek Dimensity 1200 Processor1 Year for Handset and 6 Months for In-box Accessories', '8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Display50MP Rear Camera4800 mAh Battery1 Year Manufacturer Warranty for Handset and 6 Months Warranty for In the Box Accessories', '8 GB RAM | 128 GB ROM16.94 cm (6.67 inch) Full HD+ Display108MP + 13MP + 5MP | 20MP Front Camera5000 mAh Li-ion Polymer BatteryQualcomm Snapdragon 865 Processor144Hz Intelligent AdaptiveSync Display33W Dual Split Flash Charge1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-box Accessories', '12 GB RAM | 256 GB ROM16.66 cm (6.56 inch) Full HD+ Display108MP + 8MP + 2MP | 50MP + 8MP Dual Front Camera4300 mAh Lithium BatteryMediatek Dimensity 1200 Processor1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories', '128 GB ROM15.49 cm (6.1 inch) Liquid Retina HD Display12MP + 12MP | 12MP Front CameraA13 Bionic Chip ProcessorBrand Warranty of 1 Year']
['4.5', '4.3', '4.4', '4.4', '4.4', '4.3', '4.3', '4.2', '4.3', '4.3', '4.3', '3.2', '4.2', '4.5', '4.4', '4.4', '4.2', '4.6']

In [18]:
#creating df

In [44]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
box = soup.find("div",class_ = "_1YokD2")

names =  box.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
#print(product_name)

price = box.find_all("div",class_ = "_30jeq3 _1_WHN1")

for i in price :
    price = i.text
    prices.append(price)
#print(prices)
    
desc = box.find_all("div",class_ = "fMghEO")

for i in desc :
    desc = i.text
    description.append(desc)
#print(description)

review = box.find_all("div",class_ = "_3LWZlK")

for i in review :
    review = i.text
    reviews.append(review)
#print(reviews)


df = pd.DataFrame({"Product Name":product_name,"Prices":prices,"Description":description,"Review":reviews})
print(df)

ValueError: All arrays must be of the same length

In [45]:
print(len(product_name))
print(len(prices))
print(len(description))
print(len(reviews))

24
24
24
18

In [ ]:
#df.to_csv("C:/GAURAV/Web Scrapping/flipkart_mobiles_50000.csv")

In [ ]:
# not taking reviews as they are equal in size

In [26]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(1)

r = requests.get(url)

    #print(r)

soup = BeautifulSoup(r.text,"lxml")
box = soup.find("div",class_ = "_1YokD2")

names =  box.find_all("div",class_ = "_4rR01T")
#print(names)

for i in names :
    name = i.text
    product_name.append(name)
    
#print(product_name)

price = box.find_all("div",class_ = "_30jeq3 _1_WHN1")

for i in price :
    price = i.text
    prices.append(price)
#print(prices)
    
desc = box.find_all("div",class_ = "fMghEO")

for i in desc :
    desc = i.text
    description.append(desc)
#print(description)

review = box.find_all("div",class_ = "_3LWZlK")

for i in review :
    review = i.text
    reviews.append(review)
#print(reviews)


df = pd.DataFrame({"Product Name":product_name,"Prices":prices,"Description":description})
print(df)

df.to_csv("C:/GAURAV/Web Scrapping/flipkart_mobiles_50000 new.csv")

                                         Product Name   Prices  \
0   SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...  ₹49,999
1   SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)  ₹44,999
2   MOTOROLA Edge 30 Ultra (Interstellar Black, 25...  ₹49,999
3                       Google Pixel 7 (Snow, 128 GB)  ₹47,999
4    MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)  ₹49,999
5                   Google Pixel 7 (Obsidian, 128 GB)  ₹47,999
6                 Google Pixel 7 (Lemongrass, 128 GB)  ₹47,999
7       SAMSUNG Galaxy S20 FE 5G (Cloud Mint, 128 GB)  ₹28,430
8    SAMSUNG Galaxy A54 5G (Awesome Graphite, 256 GB)  ₹40,999
9                   Nothing Phone (2) (White, 256 GB)  ₹49,999
10              Nothing Phone (2) (Dark Grey, 256 GB)  ₹49,999
11          SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)  ₹44,999
12     SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)  ₹38,999
13     SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)  ₹40,999
14       SAMSUNG Galaxy A54 5G (Awesome Lime, 256 GB)  ₹40,999
15       SAMSUNG Galaxy A73 5G (Awesome Gray, 256 GB)  ₹49,490
16           OnePlus 10T 5G (Moonstone Black, 128 GB)  ₹45,990
17                 vivo X70 Pro (Aurora Dawn, 256 GB)  ₹46,999
18                  Mi 10T Pro (Cosmic Black, 128 GB)  ₹47,999
19                vivo X70 Pro (Cosmic Black, 256 GB)  ₹45,999
20       SAMSUNG Galaxy A73 5G (Awesome Gray, 128 GB)  ₹41,999
21           vivo V23 Pro 5G (Stardust Black, 256 GB)  ₹43,990
22                      APPLE iPhone 11 (Red, 128 GB)  ₹46,999
23                OnePlus 10T 5G (Jade Green, 256 GB)  ₹48,990

                                          Description
0   8 GB RAM | 128 GB ROM16.76 cm (6.6 inch) Full ...
1   8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Full ...
2   12 GB RAM | 256 GB ROM16.94 cm (6.67 inch) Ful...
3   8 GB RAM | 128 GB ROM16.0 cm (6.3 inch) Full H...
4   12 GB RAM | 256 GB ROM16.94 cm (6.67 inch) Ful...
5   8 GB RAM | 128 GB ROM16.0 cm (6.3 inch) Full H...
6   8 GB RAM | 128 GB ROM16.0 cm (6.3 inch) Full H...
7   8 GB RAM | 128 GB ROM16.51 cm (6.5 inch) Displ...
8   8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16...
9   12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full...
10  12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full...
11  8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Full ...
12  8 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
13  8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16...
14  8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16...
15  8 GB RAM | 256 GB ROM | Expandable Upto 1 TB17...
16  8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Displ...
17  12 GB RAM | 256 GB ROM16.66 cm (6.56 inch) Ful...
18  8 GB RAM | 128 GB ROM16.94 cm (6.67 inch) Full...
19  12 GB RAM | 256 GB ROM16.66 cm (6.56 inch) Ful...
20  8 GB RAM | 128 GB ROM | Expandable Upto 1 TB17...
21  12 GB RAM | 256 GB ROM16.66 cm (6.56 inch) Ful...
22  128 GB ROM15.49 cm (6.1 inch) Liquid Retina HD...
23  12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Disp...

In [50]:
# for i in range (2,10):
    #url = "https://www.flipkart.com/search?q=mobiles%20under%2050000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
product_name =[]
prices = []
description = []
reviews= []
 
for i in range(2,12) :    
    url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page="+ str(i)

    r = requests.get(url)

        #print(r)

    soup = BeautifulSoup(r.text,"lxml")
    box = soup.find("div",class_ = "_1YokD2")

    names =  box.find_all("div",class_ = "_4rR01T")
    #print(names)

    for i in names :
        name = i.text
        product_name.append(name)

    #print(product_name)

    price = box.find_all("div",class_ = "_30jeq3 _1_WHN1")

    for i in price :
        price = i.text
        prices.append(price)
    #print(prices)

    desc = box.find_all("div",class_ = "fMghEO")

    for i in desc :
        desc = i.text
        description.append(desc)
    #print(description)

    #review = box.find_all("div",class_ = "_3LWZlK")

    #for i in review :
        #review = i.text
        #reviews.append(review)
    #print(reviews)


df = pd.DataFrame({"Product Name":product_name,"Prices":prices,"Description":description})
df.head()

#df.to_csv("C:/GAURAV/Web Scrapping/flipkart_mobiles_50000 new new.csv")

,Product Name,Prices,Description
0,"SAMSUNG Galaxy A73 5G (Awesome Gray, 128 GB)","₹41,999",8 GB RAM | 128 GB ROM | Expandable Upto 1 TB17...
1,"OnePlus 10T 5G (Jade Green, 256 GB)","₹48,990",12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Disp...
2,"OnePlus 9 Pro 5G (Stellar Black, 256 GB)","₹49,999",12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Disp...
3,"OnePlus 10 Pro 5G (Volcanic Black, 128 GB)","₹49,999",8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Displ...
4,"OnePlus 9 Pro 5G (Stellar Black, 128 GB)","₹46,888",8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Displ...

In [51]:
df.shape

(240, 3)

In [59]:
product_name = []
prices = []
description = []
reviews = []

for i in range(2,12) :
    url = "https://www.flipkart.com/search?q=mobiles+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=" + str(i)
    r = requests.get(url)

    soup = BeautifulSoup(r.text, "lxml")
    box = soup.find("div", class_="_1YokD2")

    names = box.find_all("div", class_="_4rR01T")
    for i in names:
        name = i.text
        product_name.append(name)

    price = box.find_all("div", class_="_30jeq3 _1_WHN1")
    for i in price:
        price = i.text
        prices.append(price)

    desc = box.find_all("div", class_="fMghEO")
    for i in desc:
        desc = i.text
        description.append(desc)

    review = box.find_all("div", class_="_3LWZlK")
    for i in review:
        review = i.text
        reviews.append(review)

    #lengths of lists and handle missing values
    max_length = max(len(product_name), len(prices), len(description), len(reviews))
    product_name += ['0'] * (max_length - len(product_name))
    prices += ['0'] * (max_length - len(prices))
    description += ['0'] * (max_length - len(description))
    reviews += ['0'] * (max_length - len(reviews))

df1 = pd.DataFrame({"Product Name": product_name, "Prices": prices, "Description": description, "Review": reviews})
df1.head()

,Product Name,Prices,Description,Review
0,"APPLE iPhone 11 (Red, 128 GB)","₹46,999",128 GB ROM15.49 cm (6.1 inch) Liquid Retina HD...,4.6
1,"SAMSUNG Galaxy A73 5G (Awesome Gray, 128 GB)","₹41,999",8 GB RAM | 128 GB ROM | Expandable Upto 1 TB17...,4.2
2,"OnePlus 10T 5G (Jade Green, 256 GB)","₹48,990",12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Disp...,4.2
3,"OnePlus 10 Pro 5G (Volcanic Black, 128 GB)","₹49,999",8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Displ...,3.8
4,"OnePlus 9 Pro 5G (Stellar Black, 256 GB)","₹47,990",12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Disp...,3.8

In [60]:
df1.shape

(240, 4)

In [61]:
df1["Review"].unique()

array(['4.6', '4.2', '3.8', '4', '3.9', '4.3', '0', '4.5', '4.1', '4.4',
       '3.6'], dtype=object)